"""Macro Meals, Micro Budget — Dave Fell.

Extracted from the PDF, then reviewed. Macros and prices are per serving as printed;
ingredient quantities are for the whole batch (`servings` portions).
"""

BOOK = 'Macro Meals, Micro Budget'

RECIPES = [{'title': 'Biscoff Protein Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (440, 30, 49, 13),
  'price': 0.9,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(40.0, 'g', 'oats', 'Oats'),
                  (30.0, 'g', 'protein_powder', 'Protein powder (I used Choc Honeycomb from B&M) (1 Scoop)'),
                  (150.0, 'ml', 'almond_milk', 'Milk (I used Almond)'),
                  (10.0, 'g', 'biscoff_spread', 'Biscoff spread'),
                  (2.0, 'biscuit', 'biscoff_biscuit', 'Biscoff biscuits')],
  'steps': ['Combine your 40g of oats and 150ml of milk of choice. Cook on medium heat for 3 mins.',
            'After the 3 minutes, remove your oats from the heat. Crush up 1 Biscoff biscuit and add along with your '
            'scoop of protein powder. Mix thoroughly until all combined. Adjust consistency at this point, to your '
            'liking, with either water or more milk.',
            'Put your oats into a bowl. Crush the other Biscoff biscuit up and layer the crumbs on top.',
            'Add a dash of warm water to your Biscoff spread to loosen it up. Then pour it over the top of the oats.'],
  'tips': 'Adjust the consistency to your liking. If too thin, add more protein powder. If too thick, add more milk or '
          'water',
  'swaps': 'Make vegan by swapping in your favourite vegan protein powder. The Biscoff biscuits & spread from Aldi are '
           'both vegan friendly!',
  'photo': {'page': 8, 'xref': 238}},
 {'title': 'Nutella & Banana Protein Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (482, 33, 70, 8),
  'price': 1.01,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(40.0, 'g', 'oats', 'Oats'),
                  (25.0, 'g', 'protein_powder', 'Protein powder (I used Vanilla from B&M) (1 Scoop)'),
                  (150.0, 'ml', 'almond_milk', 'Milk (I used Almond)'),
                  (5.0, 'g', 'cocoa', 'Cocoa powder'),
                  (1.0, 'banana', 'banana', 'Banana'),
                  (10.0, 'g', 'choc_hazelnut', 'Nutokka')],
  'steps': ['Combine your 40g of oats and 150ml of milk of choice. Cook on medium heat for 3 mins.',
            'After the 3 minutes, remove your oats from the heat. Add your cocoa powder along with your scoop of '
            'protein powder. Mix thoroughly until all combined. Adjust consistency at this point, to your liking, with '
            'either water or more milk.',
            'Put your oats into a bowl. Smooth the top over. Slice your banana into slices and then lay over to top.',
            'Add a dash of warm water to your Nutokka spread to loosen it up. Then pour it over the top of the oats.'],
  'tips': 'Adjust the consistency to your liking. If too thin, add more protein powder. If too thick, add more milk or '
          'water. Nutokka = Aldi’s own version of Nutella!',
  'swaps': 'Make vegan by swapping in your favourite vegan protein powder and omitting the Nutokka spread',
  'photo': {'page': 10, 'xref': 260}},
 {'title': 'Lemon-Blueberry Cheesecake Overnight Weetabix',
  'meal': 'Breakfast',
  'main': 'Weetabix',
  'tags': [],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (390, 29, 60, 3),
  'price': 1.75,
  'shop': 'ALDI/ LIDL',
  'ingredients': [(4.0, 'biscuit', 'wheat_biscuit', 'Wheat biscuits (Lidl’s own)'),
                  (160.0, 'ml', 'almond_milk', 'Almond milk (Aldi)'),
                  (2.0, 'pot', 'protein_yoghurt', 'Lemon cheesecake protein yoghurts (Aldi)'),
                  (150.0, 'g', 'blueberries', 'Fresh blueberries (Aldi)'),
                  (15.0, 'g', 'honey', 'Honey (Aldi)')],
  'steps': ['Take 2 wheat biscuits for each tub and crush them up into fine crumbs.',
            'Add 80ml of your milk of choice (I used Almond) to each tub and mix until thoroughly combined. Press into '
            'the bottom of the tub to form a base.',
            'Add your blueberries to a frying pan and start to fry on low-med heat. Add your honey to the pan and let '
            'simmer for 5 mins.',
            'Take your protein yoghurt and lay over the base. Spread over and even out.',
            'Once your blueberries form a jam, spoon half of the mix into each tub.',
            'Let cool, pop on a lid on and put in the fridge overnight or until you’re ready to eat.'],
  'tips': 'If you prefer firmer weetabix, add 50ml of milk into each tub instead of 80ml',
  'swaps': 'Make vegan by swapping in your favourite vegan yoghurt. You can swap out the Weetabix base for 40g oats '
           'and 50ml milk of choice',
  'photo': {'page': 12, 'xref': 284}},
 {'title': 'Peach Cheesecake Overnight Weetabix',
  'meal': 'Breakfast',
  'main': 'Weetabix',
  'tags': [],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (385, 31, 54, 4),
  'price': 1.35,
  'shop': 'ALDI/ LIDL',
  'ingredients': [(4.0, 'biscuit', 'wheat_biscuit', 'Wheat biscuits (Lidl’s own)'),
                  (160.0, 'ml', 'almond_milk', 'Almond milk (Aldi)'),
                  (2.0, 'pot', 'protein_yoghurt', 'Peach & passionfruit yoghurt pouches (Aldi'),
                  (250.0, 'g', 'peaches_tinned', 'Peaches (Aldi)')],
  'steps': ['Take 2 wheat biscuits for each tub and crush them up into fine crumbs.',
            'Add 80ml of your milk of choice (I used Almond) to each tub and mix until thoroughly combined. Press into '
            'the bottom of the tub to form a base.',
            'Take your yoghurt and layer over the base. Spread over and even out.',
            'Add half of your drained peaches on top of the yoghurt in each tub.',
            'Pop your lid on and put in the fridge overnight or until you’re ready to eat.'],
  'tips': 'If you prefer firmer weetabix, add 50ml of milk into each tub instead of 80ml',
  'swaps': 'Make vegan by swapping in your favourite vegan yoghurt. You can swap out the Weetabix base for 40g oats '
           'and 50ml milk of choice',
  'photo': {'page': 14, 'xref': 304}},
 {'title': 'Raspberry Cheesecake Overnight Weetabix',
  'meal': 'Breakfast',
  'main': 'Weetabix',
  'tags': [],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (357, 31, 45, 3),
  'price': 1.94,
  'shop': 'ALDI/ LIDL',
  'ingredients': [(4.0, 'biscuit', 'wheat_biscuit', 'Wheat biscuits (Lidl’s own)'),
                  (160.0, 'ml', 'oat_milk', 'Oat milk'),
                  (2.0, 'pot', 'protein_yoghurt', 'Raspberry yoghurt pouches (Aldi)'),
                  (125.0, 'g', 'raspberries', 'Raspberries (Aldi)')],
  'steps': ['Take 2 wheat biscuits for each tub and crush them up into fine crumbs.',
            'Add 80ml of your milk of choice (I used Oat) to each tub and mix until thoroughly combined. Press into '
            'the bottom of the tub to form a base.',
            'Take your protein yoghurt and layer over the base. Spread over and even out.',
            'Add half of your raspberries on top of the yoghurt in each tub. Pop your lid on and put in the fridge '
            'overnight or until you’re ready to eat.'],
  'tips': 'If you prefer firmer weetabix, add 50ml of milk into each tub instead of 80ml',
  'swaps': 'Make vegan by swapping in your favourite vegan yoghurt. You can swap out the Weetabix base for 40g oats '
           'and 50ml milk of choice',
  'photo': {'page': 16, 'xref': 321}},
 {'title': 'Mixed Berry Cheesecake Overnight Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (422, 31, 60, 6),
  'price': 1.19,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(80.0, 'g', 'oats', 'Oats'),
                  (25.0, 'g', 'protein_powder', 'Protein powder (Vanilla from B&M Bargains)'),
                  (100.0, 'ml', 'almond_milk', 'Milk of choice (Almond used)'),
                  (300.0, 'g', 'mixed_berries', 'Mixed berry medley'),
                  (400.0, 'g', 'greek_yog_ff', 'Fat free greek yoghurt'),
                  (10.0, 'g', 'honey', 'Honey'),
                  (10.0, 'g', 'lemon_juice', 'Lemon juice')],
  'steps': ['Get your 300g frozen mixed berries & add to a pan with your honey and lemon juice. Cook on low for 5 '
            'minutes.',
            'Combine 40g of oats and 50ml of milk of choice into each tub and smush it down to the bottom of the tub '
            'to form a base. Take your 400g fat free greek yoghurt and',
            'add to a bowl. Mix in 1 scoop of protein and then pour in the berry juices from your pan. Mix well.',
            'Add 1/2 of your yoghurt mixture into each tub and smooth over with a spoon. Then add half of your berry '
            'mixture into each tub. Allow to cool and then add a lid on and pop in the fridge until you’re ready to '
            'eat.'],
  'tips': 'Use the berry juice to flavour the yoghurt. Use a spoon to squash the berries if you prefer a jam like '
          'texture!',
  'swaps': 'Make vegan by swapping in your favourite vegan yoghurt & protein powder.',
  'photo': {'page': 18, 'xref': 337}},
 {'title': 'Tiramisu Overnight Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (368, 32, 42, 7),
  'price': 1.0,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(50.0, 'g', 'oats', 'Oats'),
                  (25.0, 'g', 'protein_powder', 'Protein powder (Vanilla from B&M Bargains)'),
                  (50.0, 'ml', 'almond_milk', 'Milk of choice (Almond used)'),
                  (5.0, 'g', 'cocoa', 'Cocoa powder'),
                  ('1 shot instant coffee',),
                  (50.0, 'g', 'greek_yog_ff', 'Fat free greek yoghurt'),
                  (5.0, 'g', 'cocoa', 'Cocoa powder')],
  'steps': ['Combine your 50g of oats, 1 tsp of cocoa powder and a scoop of protein in a jar. Shake your dry '
            'ingredients to mix.',
            'Then add your milk of choice and 1 shot of coffee. Mix thoroughly and then smooth the top into an even '
            'layer. Then add your 50g of fat free greek yoghurt',
            'over the top and smooth over. Then carefully sprinkle your cocoa powder over the top of the greek '
            'yoghurt. Shake gently to smooth over the top.',
            'Put a lid on your jar and refrigerate overnight or until you’re ready to eat.'],
  'tips': 'Use a sieve to evenly distribute the cocoa powder topping',
  'swaps': 'Make vegan by swapping in your favourite vegan yoghurt & protein powder.',
  'photo': {'page': 20, 'xref': 358}},
 {'title': 'Chocolate Peanut Butter Overnight Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (422, 37, 42, 14),
  'price': 1.08,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(40.0, 'g', 'oats', 'Oats'),
                  (25.0, 'g', 'protein_powder', 'Protein powder (Vanilla from B&M Bargains)'),
                  (50.0, 'ml', 'almond_milk', 'Milk of choice (Almond used)'),
                  (5.0, 'g', 'cocoa', 'Cocoa powder'),
                  (15.0, 'g', 'peanut_butter', 'Peanut butter'),
                  (100.0, 'g', 'greek_yog_ff', 'Fat free greek yoghurt')],
  'steps': ['Combine your 40g of oats, 1 tsp of cocoa powder and a scoop of protein in a jar. Shake your dry '
            'ingredients to mix.',
            'Then add your milk of choice and 100g of fat free greek yoghurt. Mix thoroughly and then smooth the top '
            'into an even layer. Take your tbsp of peanut butter and melt in',
            'the microwave for 20 seconds. Add half of your peanut butter directly into the oats and mix fully. Then '
            'add the other half over the top, however you wish.',
            'Put a lid on your jar and refrigerate overnight or until you’re ready to eat.'],
  'tips': 'Use more peanut butter if you want that to be the dominant flavour - this will increase the calories though',
  'swaps': 'Make vegan by swapping in your favourite vegan yoghurt & protein powder.',
  'photo': {'page': 22, 'xref': 381}},
 {'title': 'Banana-Mocha Protein Smoothie',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (468, 36, 74, 7),
  'price': 1.16,
  'shop': 'ALDI/ MYPROTEIN',
  'ingredients': [(100.0, 'g', 'oats', 'Oats'),
                  (2.0, 'banana', 'banana', 'Bananas'),
                  ('2 shots coffee',),
                  (75.0, 'g', 'protein_powder', 'Choc protein powder'),
                  (50.0, 'ml', 'oat_milk', 'Milk of choice (I used oat)'),
                  ('400ml water',),
                  ('2 handfuls ice',)],
  'steps': ['Put all ingredients listed into a blender.', 'Blend until smooth.'],
  'tips': 'Put second portion in fridge and shake before use.',
  'swaps': 'Make vegan by swapping in your favourite protein powder. Use your favourite coffee machine to make the '
           'shots or just instant mixed with a little bit of',
  'photo': {'page': 24, 'xref': 400}},
 {'title': 'High-Protein Chocolate French Toast Bites',
  'meal': 'Breakfast',
  'main': 'Protein powder',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (487, 35, 53, 16),
  'price': 1.72,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'bun', 'brioche_bun', 'Brioche bun'),
                  (1.0, 'egg', 'egg', 'Egg'),
                  (1.0, 'egg white', 'egg_white', 'Egg white'),
                  (25.0, 'g', 'protein_powder', 'Protein (Chocbrownie from MyProtein)'),
                  ('1/2 tsp cinnamon',),
                  ('1/2 tsp vanilla extract',),
                  (15.0, 'g', 'choc_hazelnut', 'Nutella'),
                  (0.5, 'banana', 'banana', 'Banana')],
  'steps': ['Take your egg and egg white and beat them in a bowl.',
            'Add your protein, vanilla extract, cinnamon and mix thoroughly.',
            'Cut up your brioche bun into 3cm cubes.',
            'Add to egg mixture and ensure all bread bites are completely coated in the mixture.',
            'Pan fry on med-high heat for 6-8 mins and cook until crispy.',
            'Add whatever toppings you like - I used Nutella and banana.'],
  'tips': 'Customise to your own liking using your favourite protein powder and toppings',
  'swaps': 'Swap out the brioche bun with any bread you have available in the cupboard',
  'photo': {'page': 26, 'xref': 425}},
 {'title': 'Cheesy Bacon Egg Bagels',
  'meal': 'Breakfast',
  'main': 'Pork',
  'tags': [],
  'veg': None,
  'servings': 1,
  'description': None,
  'macros': (413, 35, 28, 18),
  'price': 1.62,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'bagel thin', 'bagel_thin', 'Bagel thin'),
                  (2.0, 'egg', 'egg', 'Eggs'),
                  (2.0, 'medallion', 'bacon_medallion', 'Bacon medallions'),
                  (30.0, 'g', 'mozzarella', 'Grated mozzarella'),
                  (20.0, 'g', 'salsa', 'Tomato salsa')],
  'steps': ['Airfry or oven bake your 2 bacon medallions for 8 or 10 minutes at 190 degrees, respectively.',
            'Lay out 10g x 2, of your salsa onto a tray lined with parchment paper.',
            'Lay out your bagel thin halves over the salsa and crack 1 egg into each bagel half.',
            'Add 15g of your mozzarella onto each half and airfry for 5 mins at 190 degrees or oven bake for 8 '
            'minutes.',
            'Dice up your bacon into bits. Once the eggs are cooked, lay your bacon over the top.',
            'Optionally top with some sriracha.'],
  'tips': 'Adjust cooking time depending on how well done you like your eggs. Add a couple more minutes if you prefer '
          'them a bit harder.',
  'swaps': 'Make vegetarian by omitting the bacon medallions or subbing with your favourite veggie bacon!',
  'photo': {'page': 28, 'xref': 447}},
 {'title': 'Cheesy Breakfast Bagel Sandwich',
  'meal': 'Breakfast',
  'main': 'Pork',
  'tags': [],
  'veg': None,
  'servings': 1,
  'description': None,
  'macros': (335, 33, 27, 11),
  'price': 1.42,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'bagel thin', 'bagel_thin', 'Bagel thin'),
                  (2.0, 'chipolata', 'chicken_chipolata', 'Chicken chipolatas'),
                  (2.0, 'medallion', 'bacon_medallion', 'Bacon medallions'),
                  (25.0, 'g', 'mozzarella', 'Mozzarella')],
  'steps': ['Airfry your 2 chicken chipolatas for 7 mins at 190 degrees (or oven bake for 9 minutes).',
            'Remove from airfryer and flip your sausages. Add your bacon medallions to the same baking tray and airfry '
            'everything at 190 for a further 5 minutes (same if using an oven). Remove everything from the airfryer '
            'and lay',
            'out your bagel thin. Airfry everything once again for 1 minute at 190 (same if using an oven).',
            'Then slice your chicken sausages lengthways. Add whatever sauce you fancy to one half of your toasted '
            'bagel. Lay over the sausages, then your bacon medallions and finally your cheese. Add the top half of the '
            'bagel and airfry for 90 seconds at 190 degrees (same if using an oven).'],
  'tips': None,
  'swaps': 'Swap out the chicken chipolatas for a low calorie sausage or pork chipolata* Cheese can also be swapped '
           'out for any cheese you like* Either of these swaps will increase the calorie content',
  'photo': {'page': 30, 'xref': 468}},
 {'title': 'Scrambled Egg on Toast',
  'meal': 'Breakfast',
  'main': 'Eggs',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (405, 26, 41, 15),
  'price': 1.36,
  'shop': 'ALDI',
  'ingredients': [(2.0, 'thin', 'sandwich_thin', 'Warburtons thins'),
                  (2.0, 'egg', 'egg', 'Eggs'),
                  (20.0, 'g', 'cheddar_rf', 'Low fat cheddar cheese'),
                  (2.0, 'tomato', 'tomato', 'Tomatoes')],
  'steps': ['Take your eggs and add to a mixing bowl. Crack the yolks and mix.',
            'Add some fry light to a pan on low heat then add your eggs.',
            'Cook low and slow for 5-8 mins, stirring often.',
            'When they have formed a soft scramble (still underdone at this stage), add your cheese and tomatoes. '
            'Season with salt, pepper + paprika. Mix until thoroughly combined.',
            'Toast your bread thins and lay on a plate.',
            'Lay out your egg mixture over the top.',
            'Optional* garnish with parsley and add whatever sauce you like.'],
  'tips': None,
  'swaps': 'If using normal bread use 2 thin cut slices Swap out tomatoes for any veggies you like - spinach is also a '
           'great option for this.',
  'photo': {'page': 32, 'xref': 487}},
 {'title': 'Mixed Berry Baked Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (432, 30, 61, 7),
  'price': 1.55,
  'shop': 'ALDI/ MYPROTEIN',
  'ingredients': [(40.0, 'g', 'oats', 'Oats'),
                  (160.0, 'g', 'mixed_berries', 'Mixed frozen berries'),
                  (30.0, 'g', 'protein_powder', 'Vanilla protein'),
                  ('1/2 tsp baking powder',),
                  ('1/2 tsp vanilla extract',),
                  (125.0, 'ml', 'oat_milk', 'Oat milk')],
  'steps': ['Preheat your oven to 180 degrees.',
            'Put all of your ingredients into a blender. Saving 60g of your mixed berries.',
            'Blend until smooth.',
            'Pour into an ovenproof dish. Add your reserved berries and press into the mixture.',
            'Bake for 20 mins at 180 degrees in the oven.'],
  'tips': 'Can be cooked in the airfryer for 12 minutes at 170 degrees.',
  'swaps': 'Make Vegan by using your favourite vegan protein powder.',
  'photo': {'page': 34, 'xref': 508}},
 {'title': 'Chocolate Brownie Baked Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (452, 28, 60, 11),
  'price': 1.3,
  'shop': 'ALDI/ MYPROTEIN',
  'ingredients': [(40.0, 'g', 'oats', 'Oats'),
                  (30.0, 'g', 'protein_powder', 'Protein powder (I used choc brownie)'),
                  (0.5, 'banana', 'banana', 'Banana'),
                  ('1/2 tsp baking powder',),
                  ('1/2 tsp cinnamon',),
                  (100.0, 'ml', 'oat_milk', 'Milk of choice (i used oat)'),
                  (12.0, 'g', 'choc_chips', 'Chocolate chips')],
  'steps': ['Put all of your ingredients (exl. choc chips) into a blender.',
            'Blend until smooth.',
            'Pour into an oven safe baking dish. Top with your chocolate chips.',
            'Bake for 15 minutes at 180 degrees.'],
  'tips': 'Can be cooked in the airfryer for 10 minutes at 170 degrees.',
  'swaps': 'Make Vegan by using your favourite vegan protein powder.',
  'photo': {'page': 36, 'xref': 533}},
 {'title': 'Carrot Cake Baked Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (487, 39, 68, 7),
  'price': 1.72,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(40.0, 'g', 'oats', 'Oats'),
                  (25.0, 'g', 'protein_powder', 'Protein powder (I used Vanilla from B&M)'),
                  (200.0, 'ml', 'almond_milk', 'Milk of choice (I used almond)'),
                  (50.0, 'g', 'carrot_grated', 'Grated carrot'),
                  ('1/2 tsp baking powder',),
                  (1, 'banana', 'banana', 'Banana'),
                  ('10g dark chocolate chips (optional, not in the macros)',),
                  (50.0, 'g', 'greek_yog_ff', 'Fat free greek yoghurt'),
                  (10.0, 'g', 'protein_powder', 'Vanilla protein'),
                  ('Dash vanilla extract',)],
  'steps': ['Preheat your oven to 190 degrees. Grate your 50g carrot and banana (or mash).',
            'Add into a mixing bowl with all your other ingredients.',
            'Mix all your ingredients inc. the milk until fully combined and then add to a baking dish.',
            'Oven bake for 20 minutes at 190 degrees.',
            'Whilst that’s cooking in the oven, mix 50g fat free greek yoghurt with 10g vanilla protein and a dash of '
            'vanilla extract to make your frosting.',
            'After 20 mins, remove from the oven and allow to cool slightly. Then layer over your icing.'],
  'tips': 'Calories are excluding chocolate chips so adding them will take it above 500 calories.',
  'swaps': 'Make Vegan by using your favourite vegan protein powder and omitting the greek yoghurt.',
  'photo': {'page': 38, 'xref': 552}},
 {'title': 'Cheesy Bean Breakfast Burritos',
  'meal': 'Breakfast',
  'main': 'Eggs',
  'tags': [],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (498, 27, 48, 20),
  'price': 0.82,
  'shop': 'ALDI',
  'ingredients': [(2.0, 'wrap', 'tortilla', 'Tortilla wraps'),
                  (210.0, 'g', 'baked_beans', 'Baked beans'),
                  (45.0, 'g', 'cheddar', 'Grated cheddar'),
                  (4.0, 'egg', 'egg', 'Egg')],
  'steps': ['Get your eggs into a frying pan on low- medium heat. Scramble to your liking and then season with salt, '
            'pepper, paprika and garlic powder.',
            'Take 1 tortilla wrap and add ¼ of your cheese. Then add ½ of your eggs on top and then ¼ (105g) of a tin '
            'of baked beans. Then add another ¼ of your cheese.',
            'Repeat this step for your other wrap.',
            'Toast your wraps to seal either in a Toastie machine or on a frying pan for a couple minutes until golden '
            'brown.'],
  'tips': 'Watch the video for the burrito wrapping technique Add in whatever sauce you like before wrapping (although '
          'i didn’t!)',
  'swaps': 'If you don’t like beans, you can swapped out for vegetables such as fried tomatoes or mushrooms.',
  'photo': {'page': 40, 'xref': 571}},
 {'title': 'Cheesy Bean Muffins',
  'meal': 'Breakfast',
  'main': 'Veggie',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (471, 26, 60, 11),
  'price': 0.8,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'muffin', 'english_muffin', 'English muffin'),
                  (205.0, 'g', 'baked_beans', 'Baked beans'),
                  (20.0, 'g', 'mozzarella', 'Grated mozzarella'),
                  (1.0, 'egg', 'egg', 'Egg')],
  'steps': ['Slice your English muffin into 1/3 ‘s and lay into an ovenproof dish. Toast at 190 degrees for 2 minutes.',
            'Get your egg into a frying pan on low- medium heat.',
            'Take your par-toasted muffin. Lay over ½ (205g) a tin of baked beans and then 20g grated mozzarella. '
            'Airfry or oven bake for 6 or 8 minutes respectively at 190 degrees.',
            'Remove from the airfryer. Top with your egg.'],
  'tips': 'If you prefer your muffins more toasted, leave them in the airfryer for an extra 2 minutes.',
  'swaps': 'If you don’t like beans, you can swap out for chopped tomatoes, but you will need to heat in a pan with '
           'salt, pepper, garlic and mixed herbs - this will reduce the calories and protein.',
  'photo': {'page': 42, 'xref': 594}},
 {'title': 'BLT Wrap',
  'meal': 'Mains',
  'main': 'Pork',
  'tags': [],
  'veg': None,
  'servings': 1,
  'description': None,
  'macros': (440, 27, 37, 19),
  'price': 1.31,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'wrap', 'tortilla', 'Tortilla wrap'),
                  (4.0, 'rasher', 'bacon_rasher_rf', 'Reduced fat bacon'),
                  (40.0, 'g', 'salad_leaves', 'Mixed leaf salad'),
                  (30.0, 'g', 'cherry_tomatoes', 'Cherry tomatoes'),
                  (15.0, 'g', 'light_mayo', 'Light mayo'),
                  (5.0, 'g', 'lemon_juice', 'Lemon juice'),
                  ('1/2 tsp garlic powder',)],
  'steps': ['Get your bacon rashers into a pan and fry on medium heat for 5-7 minutes, depending on how crispy you '
            'like your bacon.',
            'Whilst your bacon is cooking, prepare your lemon-pepper mayo by combining the ingredients listed (left).',
            'Slice your cherry tomatoes into halves.',
            'Once your bacon is cooked to your liking, remove from the pan and rub your tortilla wrap in the hot pan '
            'with the bacon juices.',
            'Assemble your wrap by adding 40g of mixed salad and your sliced up tomatoes.',
            'Then add your bacon and finally layer over your sauce.',
            'Wrap your wrap into a burrito and slice down the middle.'],
  'tips': 'Watch the video for the burrito wrapping technique Add in whatever sauce you like before wrapping',
  'swaps': 'Swap bacon for 150g of seasoned chicken breast to make it higher protein Use a veggie bacon substitute to '
           'make it vegetarian',
  'photo': {'page': 45, 'xref': 654}},
 {'title': 'Chicken Caesar Wrap',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 1,
  'description': None,
  'macros': (476, 46, 39, 15),
  'price': 1.71,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'wrap', 'tortilla', 'Tortilla wrap'),
                  (1.0, 'rasher', 'bacon_rasher_rf', 'Reduced fat bacon'),
                  (130.0, 'g', 'chicken_breast', 'Chicken breast'),
                  (50.0, 'g', 'salad_leaves', 'Mixed leaf salad'),
                  (30.0, 'g', 'cherry_tomatoes', 'Cherry tomatoes'),
                  (5.0, 'g', 'lemon_juice', 'Lemon juice'),
                  (20.0, 'g', 'light_mayo', 'Light mayo'),
                  (10.0, 'g', 'parmesan', 'Parmesan'),
                  (5.0, 'g', 'lemon_juice', 'Lemon juice'),
                  ('1/2 tsp garlic powder',),
                  ('1/2 tsp salt',),
                  ('1/2 tsp black pepper',),
                  ('Dash of Worcestershire sauce',)],
  'steps': ['Slice up your rash of bacon into 4 long slices and start to pan fry on low heat.',
            'Slice up your chicken. Season with salt, pepper, garlic powder and 1 tbsp of lemon juice. Put in the air '
            'fryer or oven at 200 degrees for 8 or 10 minutes, respectively.',
            'Prepare your caesar sauce by combining the ingredients listed (left).',
            'Once your bacon is cooked to your liking, remove from the pan and rub your tortilla wrap in the hot pan '
            'with the bacon juices.',
            'Assemble your wrap by adding of mixed salad and your sliced up tomatoes. Then add your bacon, cooked '
            'chicken and finally layer over your sauce. Wrap your wrap into a burrito if you can or',
            'like a fajita if it’s too stacked like mine was (video for reference).'],
  'tips': 'Add in whatever sauce you like before wrapping',
  'swaps': 'Use Quorn (or similar) chicken pieces instead of chicken and omit the bacon to make it veggie!',
  'photo': {'page': 47, 'xref': 675}},
 {'title': 'Crispy Honey-Sriracha Chicken Wraps',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 3,
  'description': None,
  'macros': (496, 57, 50, 7),
  'price': 1.87,
  'shop': 'ALDI',
  'ingredients': [(3.0, 'wrap', 'tortilla', 'Tortilla wrap'),
                  (600.0, 'g', 'chicken_breast', 'Chicken breast mini fillets'),
                  (100.0, 'g', 'salad_leaves', 'Mixed leaf salad'),
                  (40.0, 'g', 'cornflakes', 'Cornflakes'),
                  (1.0, 'egg', 'egg_large', 'Egg'),
                  (25.0, 'g', 'sriracha', 'Sriracha'),
                  (10.0, 'g', 'honey', 'Honey')],
  'steps': ['Season your chicken breast mini fillets with salt, pepper, garlic powder & paprika. Mix fully.',
            'Crush 40g of cornflakes and season with salt, pepper, garlic powder & paprika + 1 tsp of mixed herbs.',
            'Take 1 egg and add 5g of sriracha. Whisk until fully combined.',
            'Bread your chicken by dipping into the egg mixture and then fully coating with your cornflake mix. Repeat '
            'with all your fillets.',
            'Put in the air fryer or oven at 190 degrees for 10 or 12 minutes, respectively.',
            'Whilst they’re cooking, prepare your honey- sriracha sauce by combining 10g honey with 20g sriracha.',
            'Remove tenders from airfryer. Brush each one with your sauce. Back into the oven or airfryer for 2 mins.',
            'Assemble by laying out 1 wrap and adding light mayo and then 30g of mixed leaf salad. Add 1/3 of your '
            'chicken tenders to each wrap and fold like a fajita (video for reference).'],
  'tips': 'Add in whatever sauce you like before wrapping',
  'swaps': 'You can swap out the cornflake crumb for panko or golden breadcrumbs When breading, use 1 hand for the wet '
           'ingredients and 1 hand for the dry.',
  'photo': {'page': 49, 'xref': 694}},
 {'title': 'Protein PB&J Quesadilla',
  'meal': 'Mains',
  'main': 'Protein powder',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (461, 32, 55, 13),
  'price': 0.87,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'wrap', 'tortilla', 'Tortilla wrap'),
                  (25.0, 'g', 'protein_powder', 'Vanilla protein powder (I used Vanilla from B&M)'),
                  (15.0, 'g', 'peanut_butter', 'Peanut butter'),
                  (15.0, 'g', 'jam', 'Jam'),
                  (70.0, 'g', 'greek_yog_ff', 'Fat free greek yoghurt')],
  'steps': ['Take 1 tbsp of peanut butter and microwave for 20-30 secs. Then add your scoop of protein powder and '
            'greek yoghurt and mix fully.',
            'Add your peanut butter mix to one side of a tortilla wrap and spread evenly.',
            'Then take 1 tbsp of jam and add to the other side of your wrap and spread evenly.',
            'Fold in half and press down. Heat a frying pan over medium heat and add',
            'your folded wrap on. Fry for 1-2 mins, then flip and repeat.',
            'Slice, serve and enjoy!'],
  'tips': 'Adding protein powder and peanut butter to yoghurt makes a great, high protein base for many recipes!',
  'swaps': 'You can swap out PB for any nut butter of your choice Use any jam you like - mix it up with different '
           'flavours',
  'photo': {'page': 51, 'xref': 714}},
 {'title': 'Chicken Salad Sandwich',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 1,
  'description': None,
  'macros': (355, 39, 32, 7),
  'price': 1.34,
  'shop': 'ALDI',
  'ingredients': [(130.0, 'g', 'chicken_breast', 'Chicken breast'),
                  (2.0, 'slice', 'bread_slice', 'Medium wholemeal bread'),
                  (15.0, 'g', 'salad_leaves', 'Sweet leaf salad'),
                  (15.0, 'g', 'light_mayo', 'Light mayo'),
                  (0.2, 'packet', 'seasoning_pack', 'Peri peri seasoning for the chicken')],
  'steps': ['Take your cooked chicken breast (either cook fresh with peri seasoning or buy pre- packed cooked chicken) '
            'and cut into thin slices.',
            'Lay out your 2 slices of bread and add 15g of light mayo to one side.',
            'Lay out your chicken breast evenly on the other side.',
            'Add your salad to the mayo side of the bread. Fold together to form a sandwich.',
            'Slice, serve & enjoy!'],
  'tips': 'Customise by adding any sauce you like!',
  'swaps': 'Swap out chicken for any pre-cooked meat for a super easy lunch or snack!',
  'photo': {'page': 53, 'xref': 733}},
 {'title': 'Smash Burgers',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': [],
  'veg': None,
  'servings': 2,
  'description': None,
  'macros': (468, 43, 33, 18),
  'price': 1.95,
  'shop': 'ALDI',
  'ingredients': [(250.0, 'g', 'beef_mince_5', '5% beef mince'),
                  (2.0, 'bun', 'brioche_bun', 'Brioche buns'),
                  (2.0, 'medallion', 'bacon_medallion', 'Bacon medallions'),
                  (50.0, 'g', 'mozzarella', 'Mozzarella cheese'),
                  (1.0, 'onion', 'onion', 'White onion'),
                  (10.0, 'g', 'light_spread', 'Light butter or olive spread'),
                  (10.0, 'g', 'light_mayo', 'Light mayo'),
                  (10.0, 'g', 'ketchup', 'Ketchup'),
                  (10.0, 'g', 'bbq_sauce', 'BBQ sauce'),
                  ('1/2 tsp Worcestershire sauce',),
                  ('1/2 tsp salt',),
                  ('1/2 tsp pepper',),
                  ('1/2 tsp garlic powder',)],
  'steps': ['Dice up 1 onion and add to a pan on low-med with 10g of light butter. Cook for as long as you can (until '
            'everything else is ready), stirring occasionally.',
            'Put your bacon medallions in the airfryer or oven at 190 degrees for 6 or 8 minutes respectively.',
            'Add your steak mince to a mixing bowl and season with salt, pepper, garlic powder, onion powder and '
            'paprika. Form into 4 evenly sized balls.',
            'Take an object with a flat surface and put a piece of parchment paper under it. Add your burger balls to '
            'a screaming hot pan and press down at thinly as you can. Cook for 2-3 mins, then flip and cook for a '
            'further 2 minutes. Repeat for all 4 burgers.',
            'To assemble, take your brioche bun and add your special sauce to both sides. Add one burger patty and '
            'half of your cheese slice to the Bottom bun. Then your next patty with the other half of the slice of '
            'cheese. Add 1 bacon medallion and half of your caramelised onions to each burger.',
            'Crown your burger with the top bun, wrap up in foil and heat in the oven or airfryer for 2 minutes at 190 '
            'degrees.'],
  'tips': 'Customise by adding any sauce you like! The thinner you smash the burger, the quicker it will cook so just '
          'bare that in mind!',
  'swaps': 'Swap out for any mince that you fancy, including a veggie alternative to make it vegetarian!',
  'photo': {'page': 55, 'xref': 750}},
 {'title': 'Cheesy Beef Tacos',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': [],
  'veg': None,
  'servings': 8,
  'description': 'Makes 8 tacos. Macros are per taco.',
  'macros': (269, 17, 21, 13),
  'price': 0.89,
  'shop': 'ALDI',
  'ingredients': [(360.0, 'g', 'beef_steak_thin', 'Thin cut steaks'),
                  (1.0, 'onion', 'onion', 'Red onion'),
                  (1.0, 'pepper', 'pepper', 'Red pepper'),
                  (150.0, 'g', 'mozzarella', 'Grated mozzarella'),
                  (8.0, 'tortilla', 'mini_tortilla', 'Mini tortillas'),
                  (1.0, 'packet', 'seasoning_pack', 'Taco seasoning'),
                  ('Salt',),
                  ('Pepper',),
                  ('Paprika',),
                  ('Garlic powder',)],
  'steps': ['Take your beef steaks and cut them all into thin slices.',
            'Start frying in a pan with some frylight and season with the listed seasonings + 1/2 of your taco '
            'seasoning. Once browned, set aside.',
            'Start to fry off your onion + pepper using the same seasonings as above with the beef.',
            'After 5 mins, add a dash of water to the pan and scrape up the flavour off the bottom of the pan. Re add '
            'your beef. Add 1 tbsp of lemon juice & sriracha (both optional) to the pan',
            'To make your tacos, take your mini tortilla, dip it into the beef mix and then place face down into a hot '
            'frying pan.',
            'Add 1/8 of your beef mix to the pan and top with 1/8 of your cheese to one side of the tortilla.',
            'Using a spatula, flip the other side over and press down to seal.',
            'After 1 min, flip the taco over and fry on the other side for a minute. Repeat 8 times.',
            'Optionally garnish with fresh coriander + jalapeños.'],
  'tips': 'Make sure you dip your tortilla in the beef mixture so they soak up the flavour!',
  'swaps': 'Swap out the beef for halloumi to make it vegetarian',
  'photo': {'page': 57, 'xref': 769}},
 {'title': 'Bangers & Mash',
  'meal': 'Mains',
  'main': 'Pork',
  'tags': [],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (449, 40, 53, 8),
  'price': 1.84,
  'shop': 'ALDI',
  'ingredients': [(680.0, 'g', 'potatoes', 'Potatoes'),
                  (12.0, 'sausage', 'skinny_sausage', 'Skinny sausages'),
                  (480.0, 'g', 'mixed_veg', 'Vegetable medley'),
                  (180.0, 'g', 'green_beans', 'Green beans'),
                  (15.0, 'g', 'light_spread', 'Olive spread (or butter)'),
                  (20.0, 'g', 'cream_cheese', 'Light cream cheese'),
                  ('Salt',),
                  ('Pepper',),
                  ('Paprika',),
                  ('Garlic powder',),
                  ('Salt',),
                  ('Pepper',),
                  ('Garlic powder',),
                  ('Paprika',),
                  ('Mixed Herbs',)],
  'steps': ['Take your potatoes and cut them into 2cm cubes. Get them into a pan of salted boiling water for 15 mins '
            'or until fork tender.',
            'Add your vegetable medley and green beans to an ovenproof baking dish. Spray with frylight and season '
            'using the seasonings shown (left). Roast for 20 minutes at 200 degrees.',
            'Add your sausages to a baking tray and airfry or oven bake for 14 or 18 minutes at 190 degrees '
            'respectively, flipping halfway through.',
            'Once your potatoes are fork tender, melt your light butter in a medium pan. Drain your potatoes, add to '
            'the pan and mash fully.',
            'Add your light cream cheese and seasonings to the potatoes and mix until fully combined.',
            'Once everything is cooked, plate up by dividing your mashed potato, sausages and veggies into 4 and '
            'distribute evenly.',
            'Optionally serve with gravy.'],
  'tips': None,
  'swaps': 'Swap out the sausages: for any roasted meat for an equally healthy meal For veggie ones to make it '
           'vegetarian friendly',
  'photo': {'page': 59, 'xref': 790}},
 {'title': 'Hunters Chicken Loaded Potatoes',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 1,
  'description': None,
  'macros': (454, 49, 50, 7),
  'price': 2.49,
  'shop': 'ALDI',
  'ingredients': [(150.0, 'g', 'chicken_breast', 'Pre-cooked chicken breast'),
                  (200.0, 'g', 'potatoes', 'White potato'),
                  (15.0, 'g', 'bbq_sauce', 'BBQ sauce'),
                  (30.0, 'g', 'cheddar_rf', 'Low fat cheese'),
                  ('Chilli powder',),
                  ('Garlic granules',),
                  ('Paprika',),
                  ('Salt & pepper',)],
  'steps': ['Dice your potato into 2cm cubes and add to a large mixing bowl.',
            'Season with seasonings shown (left) and lay out onto a baking tray.',
            'Air fry for 15 mins at 190 degrees or oven cook for 20 mins at 200 degrees.',
            'Take your BBQ sauce and add to a pan. Add chicken to pan and break apart with spatula.',
            'Season chicken with salt, pepper, paprika and garlic powder.',
            'Add your cooked potatoes to serving dish, top with your chicken and then low fat cheese.',
            'Microwave for 90 secs to let the cheese melt.',
            'Optionally, add some more BBQ sauce over the top.'],
  'tips': None,
  'swaps': 'Swap out the chicken for any meat or vegetarian alternative This would also work great with peri peri '
           'sauce instead of BBQ!',
  'photo': {'page': 61, 'xref': 812}},
 {'title': 'Chicken Stir Fry',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 2,
  'description': None,
  'macros': (535, 64, 52, 9),
  'price': 2.66,
  'shop': 'ASDA',
  'ingredients': [(300.0, 'g', 'chicken_breast', 'Chicken breast'),
                  (600.0, 'g', 'stir_fry_veg', 'Family stir fry bag'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (45.0, 'ml', 'soy_sauce', 'Light soy sauce'),
                  (300.0, 'g', 'noodles_ready', 'Noodles'),
                  ('Sesame seeds',)],
  'steps': ['Dice up chicken breast and add to wok.',
            'Season with salt, pepper, garlic powder, paprika and 1 tbsp of soy sauce. Once cooked, set aside.',
            'Add onion to same wok and fry for 3 mins until softened.',
            'Add bag of stir fry veg and season with salt, pepper, garlic powder, paprika and 1 tbsp of soy sauce.',
            'Fry for 5 mins or until the veg has halved in size.',
            'Add your noodles and the last tbsp of soy sauce.',
            'Add the chicken back to the wok and season one final time.',
            'Divide into 2 portions and top with sesame seeds to garnish.'],
  'tips': None,
  'swaps': 'Swap out the chicken for any meat or vegetarian alternative Can use which type of noodles you fancy - i '
           'used egg, ready to wok ones.',
  'photo': {'page': 63, 'xref': 833}},
 {'title': 'Chicken Wrap Pizzas',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 2,
  'description': 'Makes one tomato pizza (474 kcal) and one BBQ pizza (459 kcal). Macros shown are for the BBQ pizza.',
  'macros': (459, 45, 42, 12),
  'price': 1.34,
  'shop': 'ASDA',
  'ingredients': [(200.0, 'g', 'chicken_breast', 'Chicken breast'),
                  (2.0, 'wrap', 'tortilla', 'Tortilla wraps'),
                  (1.0, 'onion', 'onion', 'Red onion'),
                  (20.0, 'g', 'mushrooms', 'Mushrooms'),
                  (15.0, 'g', 'tomato_puree', 'Tomato puree'),
                  (25.0, 'g', 'bbq_sauce', 'BBQ sauce'),
                  (10.0, 'g', 'sweetcorn', 'Sweetcorn'),
                  (50.0, 'g', 'cheddar_rf', 'Reduced fat cheese')],
  'steps': ['Season chicken breast and oven cook for 20 mins @ 180 or airfry for 14 mins at 180 degrees.',
            'Dice red onion and fry for 3-4 mins.',
            'Slice mushrooms, remove half of your red onion, set aside and fry the mushrooms with the other half left '
            'in the pan.',
            'Make the tomato base using your tomato puree + salt, pepper, mixed herbs and garlic powder + dash of '
            'water. Mix until a sauce like consistency.',
            'Remove chicken from oven and slice.',
            'Start assembly by adding your bases to the wraps (1 being tomato and 1 being BBQ).',
            'Then add whatever toppings you like: For BBQ, I used chicken, sweetcorn, red onion, cheese.',
            'For tomato base I used: chicken, mushrooms, red onion, cheese.',
            'Put into a 200 degree oven for 5 mins. Remove and top with mixed herbs.'],
  'tips': 'Customise your pizza however you like with your favourite toppings',
  'swaps': 'Swap out the chicken for any meat or vegetarian alternative',
  'photo': {'page': 65, 'xref': 852}},
 {'title': 'Beefy Beef Sandwich',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': [],
  'veg': None,
  'servings': 2,
  'description': None,
  'macros': (555, 49, 54, 17),
  'price': 2.26,
  'shop': 'ALDI',
  'ingredients': [(200.0, 'g', 'beef_steak_thin', 'Thin cut beef steak'),
                  (2.0, 'roll', 'panini_roll', 'Panini rolls'),
                  (1.0, 'onion', 'onion', 'White onion'),
                  (100.0, 'g', 'mushrooms', 'Mushrooms'),
                  ('1 tsp mild French mustard',),
                  (50.0, 'g', 'cheddar_rf', 'Reduced fat cheddar')],
  'steps': ['Thinly slice your onions, mushrooms and steak.',
            'Fry the onions on med-high heat until softened.',
            'Add the beef steak in and season with salt, pepper, garlic powder and Worcestershire sauce.',
            'Add the mushrooms, then the French mustard.',
            'Slice your panini breads and lay out on tray.',
            'Add 1/2 your beef mixture to each sandwich.',
            'Add 1/2 cheese to each sandwich.',
            'Put under the grill for 3 minutes or until the cheese has melted.'],
  'tips': 'Customise your pizza however you like with your favourite toppings',
  'swaps': 'Swap out the chicken for any meat or vegetarian alternative',
  'photo': {'page': 67, 'xref': 872}},
 {'title': 'Mexican Lasagna',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': [],
  'veg': None,
  'servings': 5,
  'description': None,
  'macros': (485, 41, 39, 17),
  'price': 1.84,
  'shop': 'ALDI/ ASDA',
  'ingredients': [(3.0, 'wrap', 'tortilla', 'Tortilla wraps'),
                  (500.0, 'g', 'beef_mince_5', '5% lean beef mince'),
                  (1.0, 'packet', 'seasoning_pack', 'Taco seasoning'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (250.0, 'g', 'mozzarella', 'Grated mozzarella'),
                  (400.0, 'g', 'chopped_tomatoes', 'Chopped tomatoes'),
                  (240.0, 'g', 'kidney_beans', 'Red kidney beans')],
  'steps': ['Preheat your oven to 200 degrees Celsius. Dice your onions and fry for 3-4 mins or until softened.',
            'Add your beef mince to the pan and season with Salt, Pepper, Paprika, Garlic powder & 1/2 your taco '
            'seasoning packet. Mix thoroughly and whilst that’s cooking, dice up your peppers.',
            'Once your mince has browned, add your diced peppers and cooked for 3 minutes.',
            'Add your drained kidney beans and tin of chopped tomatoes.',
            'Season again using the same seasonings as before and the remainder of your seasoning packet.',
            'Layer your lasagna by adding a base layer of your meat mixture and then 25g grated mozzarella. Then add 1 '
            'and a 1/2 of your tortilla wraps to cover the first layer completely. Repeat this step.',
            'Add the remainder of your meat mixture over the 2nd layer of tortilla wraps and then top with the '
            'remainder (200g) of your cheese.',
            'Cook in the oven for 15 minutes. Then let rest for 5-10 mins before slicing.'],
  'tips': 'Don’t add too much cheese at the early stages as you want to save most for the top',
  'swaps': 'Swap out the mince for a veggie alternative to make it vegetarian',
  'photo': {'page': 69, 'xref': 891}},
 {'title': "World's Easiest & Healthiest Chicken Dinner",
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 2,
  'description': None,
  'macros': (366, 37, 33, 8),
  'price': 2.7,
  'shop': 'ASDA',
  'ingredients': [(300.0, 'g', 'chicken_breast', 'Chicken breasts'),
                  (350.0, 'g', 'mixed_veg', 'Mixed veg'),
                  (360.0, 'g', 'potatoes', 'Buttery & Herby Baby Potatoes'),
                  (100.0, 'ml', 'gravy', 'Gravy'),
                  ('Spice mix: tsp garlic powder tsp paprika tsp mixed herbs tsp black pepper',),
                  ('1/2 tsp red chilli flakes',),
                  ('1/2 tsp salt',)],
  'steps': ['Combine all spices listed (left) in a mug and mix.',
            'Put the veg mix on one tray and the chicken on the other. Season with the spice mix (1/2 for each tray) '
            'making sure that everything is fully coated.',
            'Put in the oven for 20 mins at 180 degrees.',
            'When there’s 8 mins left, microwave the potatoes as per pack instructions.',
            'Prep your gravy as per pack instructions.',
            'Take trays out the oven. Slice chicken.',
            'Plate everything up.'],
  'tips': None,
  'swaps': 'Swap out the chicken breasts for a veggie alternative to make it vegetarian Customise with any side '
           'potatoes that you like!',
  'photo': {'page': 71, 'xref': 912}},
 {'title': 'Chicken Fajita Salad',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (420, 38, 31, 14),
  'price': 2.4,
  'shop': 'ALDI/ ASDA',
  'ingredients': [(500.0, 'g', 'chicken_breast', 'Chicken breast'),
                  (2.0, 'onion', 'onion', 'White onions'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (300.0, 'g', 'avocado', 'Avocado'),
                  (300.0, 'g', 'tomatoes', 'Tomatoes'),
                  (2.0, 'head', 'romaine', 'Romaine lettuce'),
                  (200.0, 'g', 'cucumber', 'Cucumber'),
                  (1.0, 'packet', 'seasoning_pack', 'Fajita seasoning'),
                  (1.0, 'jar', 'jalapenos', 'Jalapeños (optional)', 170),
                  (150.0, 'g', 'salsa', 'Salsa'),
                  (100.0, 'g', 'greek_yog_ff', 'Fat free yoghurt'),
                  (15.0, 'g', 'light_mayo', 'Light mayo'),
                  (15.0, 'g', 'sriracha', 'Sriracha'),
                  (15.0, 'g', 'lemon_juice', 'Lemon juice'),
                  ('Dash jalapeño juice (optional)',)],
  'steps': ['Preheat the oven to 200 degrees.',
            'Slice your onions, peppers and chicken breast and add to a large oven proof dish. Season with salt, '
            'pepper, garlic powder and 3/4 of your fajita seasoning. Put in the oven for 20 mins.',
            'Slice up your romaine lettuce and add to the largest mixing bowl you can find.',
            'Slice up your tomatoes, avocado and cucumber and add to the mixing bowl along with your jalapeños '
            '(optional).',
            'To make your dressing, combine all of the ingredients listed (left) into a bowl.',
            'Add your dressing to the lettuce-veg mix and mix until thoroughly coated. Remove your chicken, onions and '
            'peppers',
            'from the oven. If eating straight away, serve hot with the salad. If storing for later, let cool down and '
            'mix with the salad.',
            'Portion out into 4, serve & enjoy!'],
  'tips': 'Keep the salad crunchier for longer by adding the dressing the day of eating. Try to cut everything roughly '
          'to the same size to get a mix of flavours with each bite',
  'swaps': 'Swap out the chicken breast for any protein you fancy! Customise by using your favourite veggies!',
  'photo': {'page': 74, 'xref': 956}},
 {'title': 'Salt & Pepper Chicken Noodles',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (407, 31, 65, 3),
  'price': 1.55,
  'shop': 'ALDI',
  'ingredients': [(250.0, 'g', 'egg_noodles_dry', 'Egg noodles'),
                  (320.0, 'g', 'chicken_breast', 'Chicken breasts'),
                  (2.0, 'onion', 'onion', 'White onions'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (60.0, 'g', 'spring_onions', 'Spring onions'),
                  (60.0, 'ml', 'soy_sauce', 'Light soy sauce'),
                  (1.0, 'packet', 'seasoning_pack', 'Salt n pepper seasoning'),
                  (15.0, 'g', 'cornflour', 'Cornflour')],
  'steps': ['Dice up your chicken breast into 2cm cubes. Season with salt, pepper, garlic powder, 1/3 of your SnP '
            'seasoning packet, 1 tbsp of light soy sauce and 15g cornflour.',
            'Fry in pan for 8 mins or until cooked through. Remove from the pan once done and set aside.',
            'Whilst your chicken is cooking in the pan, cut your onions and pepper into 2cm cubes. Once the chicken '
            'has been removed from the pan, fry the onions and peppers in the now empty pan for 5-6 minutes. Season '
            'with salt, pepper, garlic powder, 1/3 of your SnP seasoning packet and 1 tbsp of light soy sauce.',
            'Get your noodles onto cook as per packet instructions. Cut the white bits of your spring onions into 2cm '
            'pieces and finely slice the green bits which will be used as a garnish.',
            'Once the vegetables and noodles are cooked, add the noodles, cooked chicken and the white bits of your '
            'spring onion into the pan. Give one final seasoning of salt, pepper, garlic powder, the remaining 1/3 of '
            'your SnP seasoning packet and 1 tbsp of light soy sauce.',
            'Divide out into 4 portions and garnish with the green bits of your spring onions.'],
  'tips': 'Try and keep the cubes of chicken, onion and peppers the same size.',
  'swaps': 'Swap out the chicken breasts for any protein and/or veggie alternative you fancy Could be served alongside '
           'rice or chips instead of noodles.',
  'photo': {'page': 76, 'xref': 978}},
 {'title': 'Meatless Protein Pasta',
  'meal': 'Mains',
  'main': 'Veggie',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (470, 31, 66, 8),
  'price': 1.42,
  'shop': 'ALDI',
  'ingredients': [(100.0, 'g', 'pasta_dry', 'Pasta (dry weight)'),
                  (2.0, 'onion', 'onion', 'Red onions'),
                  (2.0, 'carrot', 'carrot', 'Carrots'),
                  (50.0, 'g', 'mozzarella', 'Mozzarella'),
                  (300.0, 'g', 'cottage_cheese', 'Fat free cottage cheese'),
                  (250.0, 'g', 'jar_sauce', 'Tomato & garlic pasta sauce'),
                  ('50ml pasta water',)],
  'steps': ['Get your pasta onto boil and cook per packed instructions.',
            'Dice up your red onions and start frying them into a frying pan with a little bit of Frylight.',
            'Dice up your carrots and add them to the frying pan. Season with salt, pepper, paprika, garlic powder and '
            'cook for 5 minutes.',
            'Reserve 50ml of your pasta water. Add your cottage cheese and tomato sauce to the blender along with your '
            'pasta water and cooked onions and carrots. Blend until smooth.',
            'Put the sauce back into the frying pan and once ready, add your cooked pasta.',
            'Add your grated mozzarella and taste for seasoning. Add more as required.',
            'Portion into 2 servings and optional garnish with parsley and red chilli flakes.'],
  'tips': 'Double up the ingredients to make 4 servings for lunches throughout the week. If you prefer a chunkier '
          'sauce, don’t add the carrots and onions when blending!',
  'swaps': 'Add in any extra protein sauce you like to boost the protein content.',
  'photo': {'page': 78, 'xref': 998}},
 {'title': 'Creamy Cheesy Fajita Chicken Pasta',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 5,
  'description': None,
  'macros': (456, 45, 48, 9),
  'price': 1.82,
  'shop': 'ALDI/ ASDA',
  'ingredients': [(600.0, 'g', 'chicken_breast', 'Chicken breast'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (1.0, 'packet', 'seasoning_pack', 'Fajita seasoning packet'),
                  (240.0, 'g', 'pasta_dry', 'Pasta (dry weight)'),
                  (200.0, 'g', 'cream_cheese', 'Reduced fat cream cheese'),
                  (2.0, 'item', 'cream_cheese', 'Light cheese triangles', 17),
                  (60.0, 'g', 'cheddar_rf', 'Low fat cheese')],
  'steps': ['Open your fajita seasoning packet and add to a bowl with 1 tsp each of salt & pepper, garlic powder, '
            'onion powder, paprika and mixed herbs and mix until combined.',
            'Cut your chicken breast in half lengthwise and season with your spice mix ensuring to save at least 3 tsp '
            'of the mix and rub in to ensure thoroughly coated. Air fry or oven cook for 200 degrees for 14 or 18 '
            'minutes, respectively.',
            'Cook pasta according to pack instructions. Slice your onions and start to fry. Season with 1 tsp of '
            'remaining spice mix.',
            'Slice your peppers and add to the onions. Add another tsp of spice mix and saute for 5-6 mins.',
            'Optionally, at this stage, add your jar of jalapeños along with some of the liquid.',
            'Add your cooked pasta to the pan along with the cream cheese and light triangles. Cut your cooked chicken '
            'into chunks and add',
            'to the pan along with any spice mix you might have left.',
            'Add your 60g of low fat cheese and mix until everything is thoroughly combined.',
            'Portion out into containers. Serve and enjoy!'],
  'tips': 'Break up the cheese triangles to ensure that you don’t end up with big chunks of it!',
  'swaps': 'Swap out the chicken breasts for any protein and/or veggie alternative you fancy If you don’t want to go '
           'to another shop for the fajita seasoning, use the peri peri version from Aldi',
  'photo': {'page': 80, 'xref': 1019}},
 {'title': 'Chicken & Mushroom Pasta',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (481, 51, 51, 8),
  'price': 1.77,
  'shop': 'ALDI',
  'ingredients': [(500.0, 'g', 'chicken_breast', 'Diced chicken breast'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (250.0, 'g', 'mushrooms', 'Sliced mushrooms'),
                  (240.0, 'g', 'pasta_dry', 'Pasta of choice (I used macaroni - dry weight)'),
                  (100.0, 'g', 'cream_cheese', 'Reduced fat cream cheese (Aldi’s own)'),
                  (300.0, 'g', 'cottage_cheese', 'Fat free cottage cheese'),
                  (200.0, 'ml', 'almond_milk', 'Almond milk'),
                  (30.0, 'g', 'mozzarella', 'Grated mozzarella'),
                  ('120ml reserved pasta water',),
                  ('Mixed herbs',),
                  ('Garlic powder',),
                  ('Salt',),
                  ('Pepper',),
                  ('Chilli paste',),
                  ('Ginger',),
                  (20.0, 'g', 'lemon_juice', 'Lemon juice')],
  'steps': ['Cook your pasta as per the packet instructions. Just before your pasta is fully cooked, reserve 120ml of '
            'pasta water.',
            'Dice up 1 onion and fry for 3-4 mins, until it starts to soften.',
            'Then add your sliced chicken and mushrooms. Season using those shown (left) and fry for 6-8 mins.',
            'Make your cheese sauce by combining your milk, cream cheese, reserved pasta water + cottage cheese into a '
            'blender and blend until smooth. Season with same seasonings used before (1 tsp lemon juice).',
            'Add your cooked and drained pasta to the pan. Then add your cheese sauce.',
            'Add in your grated mozzarella and season one final time with mixed herbs, salt and pepper.',
            'Make a cornstarch slurry and add to the pan.',
            'Cook on low until sauce has thickened to thick and creamy - this may take between 5-8 minutes.',
            'Portion out your pasta into 4 servings.'],
  'tips': 'Add less pasta water if you prefer a thicker sauce.',
  'swaps': 'Swap out the chicken breasts for any protein and/or veggie alternative you fancy',
  'photo': {'page': 82, 'xref': 1038}},
 {'title': 'Chilli Cheese Loaded Fries',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (479, 37, 66, 9),
  'price': 1.62,
  'shop': 'ALDI',
  'ingredients': [(940.0, 'g', 'potatoes', 'Potatoes'),
                  (500.0, 'g', 'beef_mince_5', '5% lean beef mince'),
                  (500.0, 'g', 'jar_sauce', 'Chilli con carne sauce'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (3.0, 'slice', 'cheese_slice', 'Light cheese slices'),
                  (25.0, 'ml', 'milk_semi', 'Semi skimmed milk'),
                  (40.0, 'g', 'jalapenos', 'Jalapeños (optional)'),
                  ('Seasonings',),
                  ('Salt',),
                  ('Pepper',),
                  ('Paprika',),
                  ('Garlic powder',),
                  ('Mixed Herbs',),
                  ('Cornflour',)],
  'steps': ['Take your potatoes and cut them all into fry shaped pieces.',
            'Add to the biggest mixing bowl you can find and coat using seasoning ingredients shown (left). Mix until '
            'thoroughly combined and lay out onto a baking tray. Airfry at 190 degrees for 20 mins or oven bake at 200 '
            'degrees for 25 mins.',
            'Start to fry off your mince and season with Salt, Pepper, Garlic powder & Paprika.',
            'Dice your onion and add to the pan with the mince when the mince is 75% browned off. Fry for 5 mins.',
            'After 5 mins, add your jar of chilli con carne mix to the pan and simmer on low until your fries are '
            'done.',
            'To make your cheese sauce, combine your milk and cheese slices in a small jug/mug. Microwave and stir '
            'every 10 seconds until the cheese has melted and a sauce has formed.',
            'When your fries are done, assemble by portioning out 4 times into each tub. Then lay a 1/4 of your chilli '
            'mix into each, followed by 1/4 of your cheese sauce and 10g each of jalapeños (optional)',
            'Pop your lid on each tub and put in the fridge or until you’re ready to eat.'],
  'tips': 'Try and keep the fries roughly the same size so they cook evenly. If you have time (can be bothered), par '
          'boil the potatoes for 10 mins and pat dry before seasoning and baking.',
  'swaps': 'Swap out the mince for a veggie alternative to make it veggie friendly.',
  'photo': {'page': 84, 'xref': 1062}},
 {'title': 'Slow Cooker Veggie Chilli',
  'meal': 'Mains',
  'main': 'Veggie',
  'tags': ['Meal prep'],
  'veg': 'VG',
  'servings': 4,
  'description': None,
  'macros': (352, 25, 51, 3),
  'price': 0.87,
  'shop': 'ALDI',
  'ingredients': [(1.0, 'onion', 'onion', 'Onion'),
                  (1.0, 'carrot', 'carrot', 'Carrot'),
                  (1.0, 'tin', 'chickpeas', 'Chickpeas', 240),
                  (1.0, 'tin', 'kidney_beans', 'Red kidney beans', 240),
                  (1.0, 'tin', 'taco_beans', 'Taco beans', 400),
                  (2.0, 'tin', 'chopped_tomatoes', 'Chopped tomatoes', 400),
                  (100.0, 'g', 'lentils_dry', 'Red split lentils'),
                  ('2 tsp cumin',),
                  ('2 tsp chilli powder',),
                  ('2 tsp garlic powder',),
                  ('2 tsp paprika',),
                  ('1 tsp onion powder',),
                  ('1 tsp mixed herbs',),
                  ('1 tsp salt',),
                  ('1 tsp pepper',),
                  ('1/2 tsp chilli flakes',),
                  ('40g reduced fat cheese (optional, not in the macros)',),
                  ('500g packet white rice (optional, not in the macros)',)],
  'steps': ['Dice up onion and pepper. Add to slow cooker.',
            'Drain chickpeas and red kidney beans.',
            'Add all tins into the slow cooker. 1/2 fill empty can of chop tomatoes with water and add.',
            'Measure out red lentils and add to slow cooker',
            'Mix and then add seasonings shown in ingredients into the pot. Mix again.',
            'Turn on slow cooker and cook for 4-5 hours on high or 6-8 hours on low.',
            'After this time, taste for seasoning. If okay, divide into 4 portions and add cheese* optional.',
            'Store and then serve when ready to enjoy! I served mine with packet white rice.'],
  'tips': 'Leave the cheese off the recipe (or use a vegan alternative) to keep the meal vegan friendly.',
  'swaps': None,
  'photo': {'page': 86, 'xref': 1083}},
 {'title': 'Chicken Alfredo Pasta',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (455, 49, 42, 10),
  'price': 1.61,
  'shop': 'ALDI/ LIDL',
  'ingredients': [(600.0, 'g', 'chicken_breast', 'Diced chicken breast'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (240.0, 'g', 'pasta_dry', 'Pasta of choice (I used spaghetti - dry weight)'),
                  (150.0, 'g', 'cream_cheese', 'Reduced fat cream cheese (Lidl’s own)'),
                  (300.0, 'ml', 'milk_semi', 'Semi-skimmed milk'),
                  (25.0, 'g', 'parmesan', 'Parmesan cheese'),
                  ('120ml reserved pasta water',),
                  ('1 tsp Paprika',),
                  ('1 tsp Oregano',),
                  ('1 tsp Garlic powder',),
                  ('½ tsp Salt',),
                  ('½ tsp Pepper',)],
  'steps': ['Cook your pasta as per the packet instructions. Just before your pasta is fully cooked, reserve 120ml of '
            'pasta water.',
            'Season your chicken using the seasonings listed left and air fry for or oven bake 190 degrees for 10 mins '
            'or 12 mins respectively, (if diced).',
            'Dice up 1 onion and fry for 3-4 mins, until it starts to soften.',
            'Make your Alfredo sauce by combining your milk, cream cheese, reserved pasta water + parmesan into a '
            'blender and blend until smooth. Season with same seasonings used before.',
            'Add your Alfredo sauce to the pan with the onion. Then add your cooked pasta.',
            'Cook on low until sauce has thickened to thick and creamy - this may take between 5-8 minutes.',
            'Portion out your pasta into 4 containers. Then repeat with your cooked chicken on top.'],
  'tips': 'Add the cooked onions to the blender when making the sauce for a thinner consistency If sauce hasn’t '
          'thickened up after 8 minutes of simmering, add cornstarch slurry to help thicken.',
  'swaps': None,
  'photo': {'page': 88, 'xref': 1107}},
 {'title': 'Cheesy Bacon Wraps',
  'meal': 'Snacks',
  'main': 'Pork',
  'tags': [],
  'veg': None,
  'servings': 3,
  'description': None,
  'macros': (204, 13, 17, 9),
  'price': 0.449,
  'shop': 'ALDI',
  'ingredients': [(3.0, 'tortilla', 'mini_tortilla', 'Mini tortilla wraps'),
                  (3.0, 'rasher', 'bacon_rasher_rf', 'Bacon'),
                  (60.0, 'g', 'mozzarella', 'Mozzarella')],
  'steps': ['Put your bacon in the air fryer or oven at 200 degrees for 8 or 10 minutes, respectively.',
            'Lay out your mini tortilla. Add any sauce you want (optional - i tried with ketchup, bbq and honey). Lay '
            'your bacon in the middle of the wrap and put 20g of your cheese on top.',
            'Pinch the middle of the edges of each side of the wrap and bring together, overlapping. Press the wrap '
            'seal side down onto a hot pan.',
            'Fry for 2-3 mins on each side.'],
  'tips': 'Customise using any sauce or cheese you like! Try different combos',
  'swaps': 'Swap out the bacon for a veggie alternative to make it veggie friendly.',
  'photo': {'page': 91, 'xref': 1154}},
 {'title': 'Cheesy Garlic Bread',
  'meal': 'Snacks',
  'main': 'Veggie',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (339, 13, 33, 17),
  'price': 0.6,
  'shop': 'ALDI',
  'ingredients': [(10.0, 'g', 'light_spread', 'Light butter or olive spread'),
                  (30.0, 'g', 'mozzarella', 'Grated mozzarella'),
                  (2.0, 'tortilla', 'mini_tortilla', 'Mini tortillas')],
  'steps': ['Take your mini wraps and lay them out.',
            'Spread 5g of your butter onto each wrap.',
            'Season with garlic powder and then mixed herbs to form a thin layer of seasoning across both the 2 wraps.',
            'Add 15g of grated cheese onto each wrap.',
            'Lay 1 wrap on top of the other.',
            'Cook in the air fryer or oven at 190 degrees for 4 or 6 minutes respectively.',
            'Slice, serve & enjoy!'],
  'tips': 'Make these higher in protein by adding some pre-cooked meat.',
  'swaps': 'Swap out the grated mozzarella for fresh or any other kind of cheese. Make into a pizza by adding tomato '
           'puree instead of the butter',
  'photo': {'page': 93, 'xref': 1171}},
 {'title': 'Chicken & Cheese Pinwheels',
  'meal': 'Snacks',
  'main': 'Chicken',
  'tags': [],
  'veg': None,
  'servings': 4,
  'description': 'Makes 24 pinwheels. Macros are per serving of 6.',
  'macros': (202, 23, 18, 5),
  'price': 1.47,
  'shop': 'ALDI',
  'ingredients': [(300.0, 'g', 'chicken_breast', 'Chicken breast'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (1.0, 'pepper', 'pepper', 'Pepper'),
                  (100.0, 'g', 'cheddar_rf', 'Low fat cheese'),
                  (3.0, 'wrap', 'protein_wrap', 'Protein wraps'),
                  ('1 tsp paprika',),
                  ('1 tsp onion powder',),
                  ('1 tsp garlic powder',),
                  ('1 tsp chilli powder',),
                  ('1 tsp mixed herbs',)],
  'steps': ['Add your spice mix to a mug and divide by 2. In one mug, add water and mix until a thick paste is made.',
            'Put your spice paste onto your chicken breasts and massage until thoroughly coated. Air fry for 15 mins '
            'at 190 degrees or oven bake for 20 mins at 200 degrees.',
            'Dice your onion and pepper and start to the fry in a pan. Add the remainder of your spice mix.',
            'Once chicken is done, shred.',
            'After 5-7 mins of frying the veggies, add your cooked chicken and 60g of your low fat cheese into the '
            'pan. Lay out your protein wrap and add a third of your',
            'mixture and ⅓ of your remaining cheese. Roll up tightly into a log and divide into 8 equal pieces.',
            'Repeat 2 more times until all your ingredients are used and lay out onto a baking tray.',
            'Put them in the air fryer for 5 mins and 180 degrees.',
            'To prepare your dipping sauce, add 30g light mayo to a dish with 1 tsp of black pepper, garlic powder and '
            'lemon juice. Mix until combined.'],
  'tips': 'Roll them up as tight as you can to ensure that they don’t unroll before or during baking!',
  'swaps': 'Swap out the chicken for a veggie alternative to make it vegetarian friendly Use normal wraps if you don’t '
           'have the protein ones',
  'photo': {'page': 95, 'xref': 1190}},
 {'title': 'Banana Iced Coffee',
  'meal': 'Snacks',
  'main': 'Protein powder',
  'tags': [],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (196, 20, 27, 2),
  'price': 1.15,
  'shop': 'ALDI/ MYPROTEIN',
  'ingredients': [(1.0, 'banana', 'banana', 'Banana'),
                  (400.0, 'ml', 'milk_skimmed', 'Milk of choice (I used skimmed)'),
                  ('4 shots coffee',),
                  ('1/2 tsp cinnamon',),
                  (30.0, 'g', 'protein_powder', 'Vanilla protein')],
  'steps': ['Put all the ingredients into a blender.', 'Blend until smooth.', 'Serve over ice and enjoy!'],
  'tips': 'Add 80g of oats to make this a full on breakfast smoothie. I just used instant coffee mixed with water for '
          'my coffee shots but if you’ve got a coffee machine, use that!',
  'swaps': 'Add chocolate protein or cocoa powder to make it chocolatey! (& omit the cinnamon) Use your favourite '
           'vegan protein powder to make it vegan',
  'photo': {'page': 97, 'xref': 1213}},
 {'title': 'Vanilla Iced Coffee',
  'meal': 'Snacks',
  'main': 'Protein powder',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (134, 21, 5, 4),
  'price': 1.49,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(200.0, 'ml', 'almond_milk', 'Milk of choice (I used almond)'),
                  ('2 shots coffee',),
                  ('1/2 tsp cinnamon',),
                  ('1/3 tsp vanilla extract',),
                  (25.0, 'g', 'protein_powder', 'Vanilla protein (I got mine from B&M)')],
  'steps': ['Put all the ingredients into a blender.', 'Blend until smooth.', 'Serve over ice and enjoy!'],
  'tips': 'Double up the ingredients to prep one to have the following day!',
  'swaps': 'Use your favourite vegan protein powder to make it vegan I just used instant coffee mixed with water for '
           'my coffee shots but if you’ve got a coffee machine, use that!',
  'photo': {'page': 99, 'xref': 1232}},
 {'title': 'Protein Brownies',
  'meal': 'Snacks',
  'main': 'Protein powder',
  'tags': [],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (152, 10, 16, 6),
  'price': 0.49,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(2.0, 'apple', 'apple', 'Apples (I used pink lady)'),
                  (30.0, 'g', 'protein_powder', 'Protein powder (I used Choc Honeycomb from B&M)'),
                  (30.0, 'g', 'cocoa', 'Cocoa powder'),
                  (2.0, 'egg', 'egg', 'Eggs'),
                  ('1 tsp (5g) baking powder',),
                  (15.0, 'g', 'choc_chips', 'Dark choc chips')],
  'steps': ['Peel your 2 apples and dice into cubes.',
            'Add your apples, eggs, protein powder, cocoa powder and baking powder into a blender and blend until '
            'smooth.',
            'Pour into a microwave safe tub with deep sides (as it could overflow!). Smooth over the top with a spoon '
            'and add your choc chips over the top.',
            'Microwave for 4 minutes. Then remove. The brownie should easily remove from the tub with a spatula. If '
            'not, microwave further in 30 seconds batches until done.',
            'Serve, slice & enjoy!'],
  'tips': None,
  'swaps': 'swap the apples for bananas if you’d prefer!',
  'photo': {'page': 101, 'xref': 1254}},
 {'title': 'Cinnamon Crunch Protein Cookies',
  'meal': 'Snacks',
  'main': 'Oats',
  'tags': [],
  'veg': 'V',
  'servings': 10,
  'description': None,
  'macros': (149, 10, 23, 2),
  'price': 0.35,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(160.0, 'g', 'oats', 'Oats'),
                  (90.0, 'g', 'protein_powder', 'Protein powder (I used Vanilla from B&M)'),
                  (3.0, 'banana', 'banana', 'Ripe bananas'),
                  ('1 tsp (5g) baking powder',),
                  ('2 tbsp (10g) cinnamon',),
                  (25.0, 'g', 'choc_chips', 'Dark choc chips')],
  'steps': ['Mash your 3 ripe bananas in a mixing bowl until fully smooth.',
            'Mix your protein powder with a small amount of water and mix into a thick paste.',
            'Then add your oats, baking powder, cinnamon and protein paste. Mix until fully combined. If the mixture '
            'is too thick, add splashes of milk. If too loose, then add more oats until a thick batter consistency.',
            'Spoon 1/10 of your mix onto a baking tray lined with parchment powder. Repeat 10 times and then using the '
            'spoon, form into cookie shapes.',
            'Optional* Add 1/10 of your dark choc chips onto the top of each cookie. Bake at 180 degrees in a '
            'preheated oven for 10-12 mins or until golden brown.'],
  'tips': 'Eat on their own or serve with greek yoghurt and fruit to make into an amazing meal',
  'swaps': 'Use your favourite vegan protein powder to make it vegan',
  'photo': {'page': 103, 'xref': 1273}},
 {'title': 'Protein Rice Krispie Bars',
  'meal': 'Snacks',
  'main': 'Protein powder',
  'tags': [],
  'veg': 'V',
  'servings': 10,
  'description': None,
  'macros': (173, 9, 14, 9),
  'price': 0.24,
  'shop': 'ALDI/ B&M BARGAINS',
  'ingredients': [(70.0, 'g', 'rice_krispies', 'Rice Krispies'),
                  (60.0, 'g', 'protein_powder', 'Protein powder (I used vanilla from B&M)'),
                  (30.0, 'g', 'honey', 'Honey'),
                  (80.0, 'g', 'peanut_butter', 'Peanut butter'),
                  (100.0, 'g', 'choc_chips', 'Dark chocolate'),
                  (15.0, 'g', 'coconut_oil', 'Coconut oil'),
                  ('Sprinkle: sea salt',)],
  'steps': ['Add your Rice Krispies, honey and peanut butter into a large mixing bowl. In a separate bowl, get your '
            'protein powder and add water until it forms a thick paste.',
            'Add your protein powder paste to the mixing bowl and mix everything until fully combined.',
            'Add to a parchment paper lined baking dish and press into the dish until evened out.',
            'Get your dark chocolate and coconut oil and microwave in 20 second batches until fully melted. Pour over '
            'the rice krispies and smooth over the top.',
            'Top with flaky salt and freeze for 1 hour or refrigerate for 3 hours until hardened.',
            'Serve, slice & enjoy!'],
  'tips': 'If they don’t fully harden after 4 hours in the fridge then put them into the freezer for 30 mins. Add the '
          'water to the protein powder bit by bit',
  'swaps': 'Use your favourite vegan protein powder & chocolate to make it vegan Can swap the Rice Crispies for either '
           'oats or Coco Pops',
  'photo': {'page': 105, 'xref': 1293}},
 {'title': 'High-Protein Tropical Smoothie Bowl',
  'meal': 'Snacks',
  'main': 'Veggie',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (312, 26, 47, 3),
  'price': 2.18,
  'shop': 'ASDA',
  'ingredients': [(1.0, 'pot', 'protein_yoghurt', 'Mango, Passionfruit & papaya protein yoghurt'),
                  (250.0, 'g', 'tropical_mix', 'Tropical smoothie mix'),
                  ('50ml water',),
                  ('20g tropical granola (optional, not in the macros)',),
                  ('50g blueberries (optional, not in the macros)',)],
  'steps': ['Add yoghurt, fruit mix and water to a blender.',
            'Blend until smooth. Stir and check consistency. Add more water as required.',
            'Add any toppings you fancy.'],
  'tips': 'Customise with any toppings you like! This recipe hangs very much in how good your blender is. The better '
          'your blender, the less water you’ll need and it will be more like a smoothie bowl',
  'swaps': 'Swap out the yoghurt for raspberry and use a berry medley to make a mixed berry version!',
  'photo': {'page': 107, 'xref': 1314}},
 {'title': 'Protein Hot Chocolate',
  'meal': 'Snacks',
  'main': 'Protein powder',
  'tags': [],
  'veg': 'V',
  'servings': 1,
  'description': None,
  'macros': (214, 31, 17, 3),
  'price': 0.9,
  'shop': 'ALDI/B&M BARGAINS',
  'ingredients': [(300.0, 'ml', 'milk_skimmed', 'Milk of choice (I used skimmed)'),
                  (25.0, 'g', 'protein_powder', 'Protein powder (I used Vanilla from B&M)'),
                  (5.0, 'g', 'cocoa', 'Cocoa powder'),
                  ('1 tsp sweetener',)],
  'steps': ['Put all the ingredients into a protein shaker.',
            'Shake until full mixed.',
            'Microwave for approx. 2 minutes or until fully warmed through.'],
  'tips': 'Add low calorie whipped cream to make this even more luxurious',
  'swaps': 'Use your favourite vegan protein powder & milk alternative to make it vegan',
  'photo': {'page': 109, 'xref': 1336}}]
