"""Macro Meals, Micro Budget — Dave Fell (2024).

Macros and prices are per serving, as printed in the book. Ingredient lists are
for the whole batch (`servings` portions).

Ingredient tuples: (qty, unit, food key from nutrition.FOODS, display name).
A one-item tuple is a seasoning/garnish with no meaningful macros.
"""

BOOK = "Macro Meals, Micro Budget"

RECIPES = [
    # ---------------------------------------------------------------- BREAKFAST
    dict(
        title="Biscoff Protein Oats", meal="Breakfast", main="Oats", veg="V",
        servings=1, macros=(440, 30, 49, 13), price=0.90, shop="Aldi / B&M Bargains",
        ingredients=[
            (40, "g", "oats", "Oats"),
            (30, "g", "protein_powder", "Protein powder (1 scoop)"),
            (150, "ml", "almond_milk", "Milk (almond used)"),
            (10, "g", "biscoff_spread", "Biscoff spread"),
            (2, "biscuit", "biscoff_biscuit", "Biscoff biscuits"),
        ],
        steps=[
            "Combine the oats and milk in a pan and cook on a medium heat for 3 minutes.",
            "Take off the heat. Crush 1 Biscoff biscuit and stir it in with the protein powder until fully combined. Adjust the consistency with water or more milk.",
            "Spoon into a bowl, crush the other biscuit and scatter the crumbs over the top.",
            "Loosen the Biscoff spread with a dash of warm water and pour it over the oats.",
        ],
        tips="Too thin? Add more protein powder. Too thick? Add more milk or water.",
        swaps="Use a vegan protein powder to make it vegan. Aldi's Biscoff biscuits and spread are both vegan friendly.",
    ),
    dict(
        title="Nutella & Banana Protein Oats", meal="Breakfast", main="Oats", veg="V",
        servings=1, macros=(482, 33, 70, 8), price=1.01, shop="Aldi / B&M Bargains",
        ingredients=[
            (40, "g", "oats", "Oats"),
            (25, "g", "protein_powder", "Vanilla protein powder (1 scoop)"),
            (150, "ml", "almond_milk", "Milk (almond used)"),
            (5, "g", "cocoa", "Cocoa powder"),
            (1, "banana", "banana", "Medium banana"),
            (10, "g", "choc_hazelnut", "Nutokka (Aldi's Nutella)"),
        ],
        steps=[
            "Combine the oats and milk in a pan and cook on a medium heat for 3 minutes.",
            "Take off the heat, add the cocoa and protein powder and mix until fully combined. Adjust the consistency with water or more milk.",
            "Spoon into a bowl, smooth the top and lay the sliced banana over it.",
            "Loosen the Nutokka with a dash of warm water and pour it over the oats.",
        ],
        tips="Nutokka is Aldi's own version of Nutella.",
        swaps="Use a vegan protein powder and leave out the Nutokka to make it vegan.",
    ),
    dict(
        title="Lemon-Blueberry Cheesecake Overnight Weetabix", meal="Breakfast", main="Weetabix", veg="V",
        servings=2, macros=(390, 29, 60, 3), price=1.75, shop="Aldi / Lidl",
        ingredients=[
            (4, "biscuit", "wheat_biscuit", "Wheat biscuits (Weetabix)"),
            (160, "ml", "almond_milk", "Almond milk"),
            (2, "pot", "protein_yoghurt", "Lemon cheesecake protein yoghurts"),
            (150, "g", "blueberries", "Fresh blueberries"),
            (15, "g", "honey", "Honey"),
        ],
        steps=[
            "Crush 2 wheat biscuits into fine crumbs in each tub.",
            "Add 80ml of milk to each tub, mix well and press down to form a base.",
            "Cook the blueberries and honey in a frying pan on a low-medium heat for 5 minutes until jammy.",
            "Spread a protein yoghurt over each base.",
            "Spoon half of the blueberry jam into each tub. Let cool, put the lids on and refrigerate overnight.",
        ],
        tips="For firmer Weetabix, use 50ml of milk per tub instead of 80ml.",
        swaps="Use a vegan yoghurt to make it vegan. Swap the Weetabix base for 40g oats and 50ml milk.",
    ),
    dict(
        title="Peach Cheesecake Overnight Weetabix", meal="Breakfast", main="Weetabix", veg="V",
        servings=2, macros=(385, 31, 54, 4), price=1.35, shop="Aldi / Lidl",
        ingredients=[
            (4, "biscuit", "wheat_biscuit", "Wheat biscuits (Weetabix)"),
            (160, "ml", "almond_milk", "Almond milk"),
            (2, "pouch", "protein_yoghurt", "Peach & passionfruit yoghurt pouches"),
            (250, "g", "peaches_tinned", "Tinned peaches, drained"),
        ],
        steps=[
            "Crush 2 wheat biscuits into fine crumbs in each tub.",
            "Add 80ml of milk to each tub, mix well and press down to form a base.",
            "Spread a yoghurt pouch over each base.",
            "Top each tub with half of the drained peaches. Put the lids on and refrigerate overnight.",
        ],
        tips="For firmer Weetabix, use 50ml of milk per tub instead of 80ml.",
        swaps="Use a vegan yoghurt to make it vegan. Swap the Weetabix base for 40g oats and 50ml milk.",
    ),
    dict(
        title="Raspberry Cheesecake Overnight Weetabix", meal="Breakfast", main="Weetabix", veg="V",
        servings=2, macros=(357, 31, 45, 3), price=1.94, shop="Aldi / Lidl",
        ingredients=[
            (4, "biscuit", "wheat_biscuit", "Wheat biscuits (Weetabix)"),
            (160, "ml", "oat_milk", "Oat milk"),
            (2, "pouch", "protein_yoghurt", "Raspberry yoghurt pouches"),
            (125, "g", "raspberries", "Raspberries"),
        ],
        steps=[
            "Crush 2 wheat biscuits into fine crumbs in each tub.",
            "Add 80ml of milk to each tub, mix well and press down to form a base.",
            "Spread a yoghurt pouch over each base.",
            "Top each tub with half of the raspberries. Put the lids on and refrigerate overnight.",
        ],
        tips="For firmer Weetabix, use 50ml of milk per tub instead of 80ml.",
        swaps="Use a vegan yoghurt to make it vegan. Swap the Weetabix base for 40g oats and 50ml milk.",
    ),
    dict(
        title="Mixed Berry Cheesecake Overnight Oats", meal="Breakfast", main="Oats", veg="V",
        servings=2, macros=(422, 31, 60, 6), price=1.19, shop="Aldi / B&M Bargains",
        ingredients=[
            (80, "g", "oats", "Oats"),
            (25, "g", "protein_powder", "Vanilla protein powder (1 scoop)"),
            (100, "ml", "almond_milk", "Milk (almond used)"),
            (300, "g", "mixed_berries", "Frozen mixed berries"),
            (400, "g", "greek_yog_ff", "Fat-free Greek yoghurt"),
            (10, "g", "honey", "Honey"),
            ("2 tsp lemon juice",),
        ],
        steps=[
            "Cook the berries with the honey and lemon juice in a pan on a low heat for 5 minutes.",
            "Put 40g oats and 50ml milk into each tub and press down to form a base.",
            "Mix the yoghurt with the protein powder, then stir in the juice from the berry pan.",
            "Spoon half of the yoghurt into each tub and smooth over, then top each with half of the berries. Let cool, put the lids on and refrigerate.",
        ],
        tips="Use the berry juice to flavour the yoghurt. Squash the berries with a spoon for a jammier texture.",
        swaps="Use a vegan yoghurt and protein powder to make it vegan.",
    ),
    dict(
        title="Tiramisu Overnight Oats", meal="Breakfast", main="Oats", veg="V",
        servings=1, macros=(368, 32, 42, 7), price=1.00, shop="Aldi / B&M Bargains",
        ingredients=[
            (50, "g", "oats", "Oats"),
            (25, "g", "protein_powder", "Vanilla protein powder (1 scoop)"),
            (50, "ml", "almond_milk", "Milk (almond used)"),
            (10, "g", "cocoa", "Cocoa powder (half in, half on top)"),
            (50, "g", "greek_yog_ff", "Fat-free Greek yoghurt (topping)"),
            ("1 shot instant coffee",),
        ],
        steps=[
            "Shake the oats, 1 tsp of cocoa and the protein powder together in a jar.",
            "Add the milk and coffee, mix thoroughly and smooth the top.",
            "Spread the yoghurt over the top and sieve over the remaining cocoa.",
            "Put the lid on and refrigerate overnight.",
        ],
        tips="Use a sieve to dust the cocoa evenly.",
        swaps="Use a vegan yoghurt and protein powder to make it vegan.",
    ),
    dict(
        title="Chocolate Peanut Butter Overnight Oats", meal="Breakfast", main="Oats", veg="V",
        servings=1, macros=(422, 37, 42, 14), price=1.08, shop="Aldi / B&M Bargains",
        ingredients=[
            (40, "g", "oats", "Oats"),
            (25, "g", "protein_powder", "Vanilla protein powder (1 scoop)"),
            (50, "ml", "almond_milk", "Milk (almond used)"),
            (5, "g", "cocoa", "Cocoa powder"),
            (15, "g", "peanut_butter", "Peanut butter"),
            (100, "g", "greek_yog_ff", "Fat-free Greek yoghurt"),
        ],
        steps=[
            "Shake the oats, cocoa and protein powder together in a jar.",
            "Add the milk and yoghurt, mix thoroughly and smooth the top.",
            "Microwave the peanut butter for 20 seconds. Stir half into the oats and drizzle the rest over the top.",
            "Put the lid on and refrigerate overnight.",
        ],
        tips="Add more peanut butter for a stronger flavour (it adds calories).",
        swaps="Use a vegan yoghurt and protein powder to make it vegan.",
    ),
    dict(
        title="Banana-Mocha Protein Smoothie", meal="Breakfast", main="Protein powder", veg="V",
        servings=2, macros=(468, 36, 74, 7), price=1.16, shop="Aldi / MyProtein",
        ingredients=[
            (100, "g", "oats", "Oats"),
            (2, "banana", "banana", "Bananas"),
            (75, "g", "protein_powder", "Chocolate protein powder (3 scoops)"),
            (50, "ml", "oat_milk", "Milk (oat used)"),
            ("2 shots of coffee",),
            ("400ml water and 2 handfuls of ice",),
        ],
        steps=[
            "Put everything into a blender.",
            "Blend until smooth.",
        ],
        tips="Keep the second portion in the fridge and shake before drinking.",
        swaps="Use a vegan protein powder to make it vegan. Instant coffee mixed with a little hot water works fine.",
    ),
    dict(
        title="High-Protein Chocolate French Toast Bites", meal="Breakfast", main="Eggs", veg="V",
        servings=1, macros=(487, 35, 53, 16), price=1.72, shop="Aldi",
        ingredients=[
            (1, "bun", "brioche_bun", "Brioche bun"),
            (1, "egg", "egg", "Egg"),
            (1, "egg white", "egg_white", "Egg white"),
            (25, "g", "protein_powder", "Chocolate protein powder (1 scoop)"),
            (15, "g", "choc_hazelnut", "Nutella (topping)"),
            (0.5, "banana", "banana", "Banana (topping)"),
            ("½ tsp cinnamon and ½ tsp vanilla extract",),
        ],
        steps=[
            "Beat the egg and egg white in a bowl.",
            "Whisk in the protein powder, vanilla and cinnamon.",
            "Cut the brioche into 3cm cubes and toss in the egg mixture until fully coated.",
            "Pan fry on a medium-high heat for 6–8 minutes until crispy.",
            "Top with Nutella and banana, or whatever you like.",
        ],
        tips="Use your favourite protein powder flavour and toppings.",
        swaps="Any bread you have in the cupboard works in place of the brioche.",
    ),
    dict(
        title="Cheesy Bacon Egg Bagels", meal="Breakfast", main="Eggs",
        servings=1, macros=(413, 35, 28, 18), price=1.62, shop="Aldi",
        ingredients=[
            (1, "bagel thin", "bagel_thin", "Bagel thin"),
            (2, "egg", "egg", "Eggs"),
            (2, "medallion", "bacon_medallion", "Bacon medallions"),
            (30, "g", "mozzarella", "Grated mozzarella"),
            (20, "g", "salsa", "Tomato salsa"),
            ("Sriracha, to serve (optional)",),
        ],
        steps=[
            "Air fry the bacon for 8 minutes at 190°C (or oven bake for 10).",
            "Spoon 10g of salsa per bagel half onto a lined tray.",
            "Lay the bagel halves over the salsa and crack an egg into each.",
            "Top each with 15g mozzarella and air fry for 5 minutes at 190°C (or oven bake for 8).",
            "Dice the bacon and scatter over the eggs. Finish with sriracha if you like.",
        ],
        tips="Add a couple of minutes if you like your eggs firmer.",
        swaps="Leave out the bacon or use a veggie bacon to make it vegetarian.",
    ),
    dict(
        title="Cheesy Breakfast Bagel Sandwich", meal="Breakfast", main="Sausage",
        servings=1, macros=(335, 33, 27, 11), price=1.42, shop="Aldi",
        ingredients=[
            (1, "bagel thin", "bagel_thin", "Bagel thin"),
            (2, "chipolata", "chicken_chipolata", "Chicken chipolatas"),
            (2, "medallion", "bacon_medallion", "Bacon medallions"),
            (25, "g", "mozzarella", "Mozzarella (1 slice)"),
            ("Sauce of your choice",),
        ],
        steps=[
            "Air fry the chipolatas for 7 minutes at 190°C (or oven bake for 9).",
            "Flip the sausages, add the bacon to the tray and cook for 5 minutes more.",
            "Add the bagel thin and toast for 1 minute.",
            "Slice the sausages lengthways. Spread sauce on the bagel, then layer the sausages, bacon and cheese. Close and heat for 90 seconds.",
        ],
        tips="",
        swaps="Use low-calorie or pork chipolatas, or any cheese you like (both add calories).",
    ),
    dict(
        title="Cheesy Scrambled Egg on Toast", meal="Breakfast", main="Eggs", veg="V",
        servings=1, macros=(405, 26, 41, 15), price=1.36, shop="Aldi",
        ingredients=[
            (2, "thin", "sandwich_thin", "Warburtons sandwich thins"),
            (2, "egg", "egg", "Eggs"),
            (20, "g", "cheddar_rf", "Low-fat cheddar"),
            (2, "tomato", "tomato", "Tomatoes, chopped"),
            ("Salt, pepper, paprika and parsley",),
        ],
        steps=[
            "Whisk the eggs in a bowl.",
            "Spray a pan with Frylight and cook the eggs low and slow for 5–8 minutes, stirring often.",
            "While still slightly underdone, stir in the cheese and tomatoes and season with salt, pepper and paprika.",
            "Toast the thins and spoon the eggs over the top. Garnish with parsley.",
        ],
        tips="",
        swaps="Use 2 thin slices of normal bread instead of the thins. Spinach works well in place of the tomatoes.",
    ),
    dict(
        title="Mixed Berry Baked Oats", meal="Breakfast", main="Oats", veg="V",
        servings=1, macros=(432, 30, 61, 7), price=1.55, shop="Aldi / MyProtein",
        ingredients=[
            (40, "g", "oats", "Oats"),
            (160, "g", "mixed_berries", "Frozen mixed berries"),
            (30, "g", "protein_powder", "Vanilla protein powder"),
            (125, "ml", "oat_milk", "Oat milk"),
            ("½ tsp baking powder and ½ tsp vanilla extract",),
        ],
        steps=[
            "Preheat the oven to 180°C.",
            "Blend everything until smooth, holding back 60g of the berries.",
            "Pour into an ovenproof dish and press the reserved berries into the top.",
            "Bake for 20 minutes.",
        ],
        tips="Or air fry for 12 minutes at 170°C.",
        swaps="Use a vegan protein powder to make it vegan.",
    ),
    dict(
        title="Chocolate Brownie Baked Oats", meal="Breakfast", main="Oats", veg="V",
        servings=1, macros=(452, 28, 60, 11), price=1.30, shop="Aldi / MyProtein",
        ingredients=[
            (40, "g", "oats", "Oats"),
            (30, "g", "protein_powder", "Chocolate brownie protein powder"),
            (0.5, "banana", "banana", "Banana"),
            (100, "ml", "oat_milk", "Milk (oat used)"),
            (12, "g", "choc_chips", "Chocolate chips"),
            ("½ tsp baking powder, ½ tsp cinnamon, ½ tsp vanilla (optional)",),
        ],
        steps=[
            "Blend everything except the chocolate chips until smooth.",
            "Pour into an ovenproof dish and top with the chocolate chips.",
            "Bake for 15 minutes at 180°C.",
        ],
        tips="Or air fry for 10 minutes at 170°C.",
        swaps="Use a vegan protein powder to make it vegan.",
    ),
    dict(
        title="Carrot Cake Baked Oats", meal="Breakfast", main="Oats", veg="V",
        servings=1, macros=(487, 39, 68, 7), price=1.38, shop="Aldi / B&M Bargains",
        ingredients=[
            (40, "g", "oats", "Oats"),
            (25, "g", "protein_powder", "Vanilla protein powder (1 scoop)"),
            (200, "ml", "almond_milk", "Milk (almond used)"),
            (50, "g", "carrot_grated", "Grated carrot"),
            (1, "banana", "banana", "Banana, mashed"),
            (50, "g", "greek_yog_ff", "Fat-free Greek yoghurt (frosting)"),
            (10, "g", "protein_powder", "Vanilla protein powder (frosting)"),
            ("½ tsp baking powder and a dash of vanilla extract",),
            ("10g dark chocolate chips (optional, not in the macros)",),
        ],
        steps=[
            "Preheat the oven to 190°C.",
            "Mix the oats, protein, milk, carrot, banana and baking powder until fully combined, then tip into a baking dish.",
            "Bake for 20 minutes.",
            "Meanwhile, mix the yoghurt with the frosting protein and vanilla.",
            "Let the oats cool slightly, then spread the frosting over the top.",
        ],
        tips="The macros exclude the chocolate chips; adding them takes it over 500 kcal.",
        swaps="Use a vegan protein powder and leave out the Greek yoghurt to make it vegan.",
    ),
    dict(
        title="Cheesy Bean Breakfast Burritos", meal="Breakfast", main="Eggs", veg="V",
        servings=2, macros=(498, 27, 48, 20), price=0.82, shop="Aldi",
        ingredients=[
            (2, "wrap", "tortilla", "Tortilla wraps"),
            (210, "g", "baked_beans", "Baked beans (½ tin)"),
            (45, "g", "cheddar", "Grated cheddar"),
            (4, "egg", "egg", "Medium eggs"),
            ("Salt, pepper, paprika and garlic powder",),
        ],
        steps=[
            "Scramble the eggs in a pan on a low-medium heat and season with salt, pepper, paprika and garlic powder.",
            "Lay out a wrap and add a quarter of the cheese, half the eggs, half the beans, then another quarter of the cheese.",
            "Repeat with the second wrap and roll both into burritos.",
            "Toast in a toastie machine or frying pan for a couple of minutes until golden.",
        ],
        tips="Add any sauce you like before wrapping.",
        swaps="Not a fan of beans? Use fried tomatoes or mushrooms instead.",
    ),
    dict(
        title="Cheesy Bean Muffins", meal="Breakfast", main="Beans", veg="V",
        servings=1, macros=(471, 26, 60, 11), price=0.80, shop="Aldi",
        ingredients=[
            (1, "muffin", "english_muffin", "English muffin"),
            (205, "g", "baked_beans", "Baked beans (½ tin)"),
            (20, "g", "mozzarella", "Grated mozzarella"),
            (1, "egg", "egg", "Medium egg"),
        ],
        steps=[
            "Slice the muffin, lay it in an ovenproof dish and toast at 190°C for 2 minutes.",
            "Fry the egg in a pan on a low-medium heat.",
            "Top the muffin with the beans and mozzarella and air fry for 6 minutes at 190°C (or oven bake for 8).",
            "Top with the egg.",
        ],
        tips="Leave in for an extra 2 minutes if you like the muffin crispier.",
        swaps="Swap the beans for chopped tomatoes heated with salt, pepper, garlic and herbs (fewer calories and less protein).",
    ),

    # -------------------------------------------------------------------- MAINS
    dict(
        title="BLT Wrap", meal="Mains", main="Bacon",
        servings=1, macros=(440, 27, 37, 19), price=1.31, shop="Aldi",
        ingredients=[
            (1, "wrap", "tortilla", "Tortilla wrap"),
            (4, "rasher", "bacon_rasher_rf", "Reduced-fat bacon rashers"),
            (40, "g", "salad_leaves", "Mixed leaf salad"),
            (30, "g", "cherry_tomatoes", "Cherry tomatoes, halved"),
            (15, "g", "light_mayo", "Light mayo (lemon-pepper sauce)"),
            ("1 tsp lemon juice, ½ tsp garlic powder and black pepper (for the sauce)",),
        ],
        steps=[
            "Fry the bacon on a medium heat for 5–7 minutes, depending on how crispy you like it.",
            "Meanwhile, mix the mayo, lemon juice, garlic powder and pepper.",
            "Rub the wrap around the hot pan to soak up the bacon juices.",
            "Fill with the salad and tomatoes, then the bacon and sauce.",
            "Roll into a burrito and slice down the middle.",
        ],
        tips="Add any sauce you like before wrapping.",
        swaps="Use 150g seasoned chicken breast instead of bacon for more protein, or a veggie bacon to make it vegetarian.",
    ),
    dict(
        title="Chicken Caesar Wrap", meal="Mains", main="Chicken",
        servings=1, macros=(476, 46, 39, 15), price=1.71, shop="Aldi",
        ingredients=[
            (1, "wrap", "tortilla", "Tortilla wrap"),
            (1, "rasher", "bacon_rasher_rf", "Reduced-fat bacon rasher"),
            (130, "g", "chicken_breast", "Chicken breast"),
            (50, "g", "salad_leaves", "Mixed leaf salad"),
            (30, "g", "cherry_tomatoes", "Cherry tomatoes"),
            (20, "g", "light_mayo", "Light mayo (Caesar sauce)"),
            (10, "g", "parmesan", "Parmesan (Caesar sauce)"),
            ("Lemon juice, garlic powder, salt, pepper and a dash of Worcestershire sauce",),
        ],
        steps=[
            "Slice the bacon into 4 long strips and fry on a low heat.",
            "Slice the chicken, season with salt, pepper, garlic powder and lemon juice, and air fry at 200°C for 8 minutes (or oven bake for 10).",
            "Mix the mayo, parmesan, lemon juice, garlic powder, salt, pepper and Worcestershire sauce to make the Caesar sauce.",
            "Rub the wrap around the hot bacon pan.",
            "Fill with the salad, tomatoes, bacon and chicken, then the sauce. Roll up like a burrito or fold like a fajita.",
        ],
        tips="",
        swaps="Use Quorn pieces and leave out the bacon to make it vegetarian.",
    ),
    dict(
        title="Crispy Honey-Sriracha Chicken Wraps", meal="Mains", main="Chicken",
        servings=3, macros=(496, 57, 50, 7), price=1.87, shop="Aldi",
        ingredients=[
            (3, "wrap", "tortilla", "Tortilla wraps"),
            (600, "g", "chicken_breast", "Chicken breast mini fillets"),
            (100, "g", "salad_leaves", "Mixed leaf salad"),
            (40, "g", "cornflakes", "Cornflakes"),
            (1, "egg", "egg_large", "Large egg"),
            (25, "g", "sriracha", "Sriracha"),
            (10, "g", "honey", "Honey"),
            ("Salt, pepper, garlic powder, paprika and mixed herbs",),
            ("Light mayo, to serve",),
        ],
        steps=[
            "Season the chicken with salt, pepper, garlic powder and paprika.",
            "Crush the cornflakes and season the same way, plus a teaspoon of mixed herbs.",
            "Whisk the egg with 5g of the sriracha.",
            "Dip each fillet in the egg, then coat in the cornflakes.",
            "Air fry at 190°C for 10 minutes (or oven bake for 12).",
            "Mix the honey with the remaining 20g sriracha, brush over the tenders and cook for 2 minutes more.",
            "Spread each wrap with light mayo, add 30g salad and a third of the chicken, and fold like a fajita.",
        ],
        tips="Use one hand for the wet coating and one for the dry.",
        swaps="Panko or golden breadcrumbs work instead of cornflakes.",
    ),
    dict(
        title="Protein PB&J Quesadilla", meal="Mains", main="Protein powder", veg="V",
        servings=1, macros=(461, 32, 55, 13), price=0.87, shop="Aldi",
        ingredients=[
            (1, "wrap", "tortilla", "Tortilla wrap"),
            (25, "g", "protein_powder", "Vanilla protein powder (1 scoop)"),
            (15, "g", "peanut_butter", "Peanut butter"),
            (15, "g", "jam", "Jam"),
            (70, "g", "greek_yog_ff", "Fat-free Greek yoghurt"),
        ],
        steps=[
            "Microwave the peanut butter for 20–30 seconds, then mix in the protein powder and yoghurt.",
            "Spread the peanut butter mix over one half of the wrap.",
            "Spread the jam over the other half.",
            "Fold in half and press down.",
            "Fry in a pan on a medium heat for 1–2 minutes each side. Slice and serve.",
        ],
        tips="Protein powder and peanut butter mixed into yoghurt makes a great high-protein base for lots of recipes.",
        swaps="Use any nut butter or jam you like.",
    ),
    dict(
        title="Peri Peri Chicken Salad Sandwich", meal="Mains", main="Chicken",
        servings=1, macros=(355, 39, 32, 7), price=1.34, shop="Aldi",
        ingredients=[
            (130, "g", "chicken_cooked", "Cooked chicken breast"),
            (80, "g", "wholemeal_bread", "Medium wholemeal bread (2 slices)"),
            (15, "g", "salad_leaves", "Sweet leaf salad"),
            (15, "g", "light_mayo", "Light mayo"),
            ("⅕ packet peri peri seasoning",),
        ],
        steps=[
            "Cook the chicken with the peri peri seasoning (or use ready-cooked chicken) and slice thinly.",
            "Spread the mayo over one slice of bread.",
            "Lay the chicken over the other slice.",
            "Add the salad, close the sandwich, slice and serve.",
        ],
        tips="Add any sauce you like.",
        swaps="Any pre-cooked meat works for a super easy lunch.",
    ),
    dict(
        title="Smash Burgers", meal="Mains", main="Beef",
        servings=2, macros=(468, 43, 33, 18), price=1.95, shop="Aldi",
        ingredients=[
            (250, "g", "beef_mince_5", "5% fat beef mince"),
            (2, "bun", "brioche_bun", "Brioche buns"),
            (2, "medallion", "bacon_medallion", "Bacon medallions"),
            (50, "g", "mozzarella", "Mozzarella (2 slices)"),
            (1, "onion", "onion", "White onion, diced"),
            (10, "g", "light_spread", "Light butter or olive spread"),
            (10, "g", "light_mayo", "Light mayo (special sauce)"),
            (10, "g", "ketchup", "Ketchup (special sauce)"),
            (10, "g", "bbq_sauce", "BBQ sauce (special sauce)"),
            ("½ tsp Worcestershire sauce, salt, pepper and garlic powder (special sauce)",),
            ("Salt, pepper, garlic powder, onion powder and paprika (for the beef)",),
        ],
        steps=[
            "Cook the onion in the butter on a low-medium heat for as long as you can while you make everything else, stirring now and then.",
            "Air fry the bacon at 190°C for 6 minutes (or oven bake for 8).",
            "Season the mince and roll into 4 even balls.",
            "Put the balls in a screaming hot pan and press down as thinly as you can using something flat and a sheet of baking paper. Cook for 2–3 minutes, flip and cook for 2 more.",
            "Spread the special sauce on both halves of each bun. Stack a patty and half a cheese slice, then the second patty and the rest of the cheese, then the bacon and onions.",
            "Wrap in foil and heat for 2 minutes at 190°C.",
        ],
        tips="The thinner you smash them, the faster they cook.",
        swaps="Use any mince you like, including a veggie mince.",
    ),
    dict(
        title="Cheesy Beef Tacos", meal="Mains", main="Beef",
        servings=8, macros=(269, 17, 21, 13), price=0.89, shop="Aldi",
        description="Makes 8 tacos. Macros are per taco.",
        ingredients=[
            (360, "g", "beef_steak_thin", "Thin-cut beef steaks"),
            (1, "onion", "onion", "Red onion"),
            (1, "pepper", "pepper", "Red pepper"),
            (150, "g", "mozzarella", "Grated mozzarella"),
            (8, "tortilla", "mini_tortilla", "Mini tortillas"),
            (1, "packet", "seasoning_pack", "Taco seasoning"),
            ("Salt, pepper, paprika and garlic powder",),
            ("Lemon juice and sriracha (optional); coriander and jalapeños to garnish",),
        ],
        steps=[
            "Slice the steaks thinly. Fry in Frylight with the seasonings and half the taco seasoning until browned, then set aside.",
            "Fry the onion and pepper with the same seasonings for 5 minutes.",
            "Add a splash of water and scrape up the bits from the pan, then return the beef. Add lemon juice and sriracha if you like.",
            "Dip a tortilla into the beef juices and place it face down in a hot pan.",
            "Add an eighth of the beef and an eighth of the cheese to one side, fold over and press to seal.",
            "Cook for a minute, flip and cook for another minute. Repeat to make 8.",
        ],
        tips="Dip the tortillas in the beef mixture so they soak up the flavour.",
        swaps="Use halloumi instead of beef to make it vegetarian.",
    ),
    dict(
        title="Bangers & Mash", meal="Mains", main="Sausage",
        servings=4, macros=(449, 40, 53, 8), price=1.84, shop="Aldi",
        ingredients=[
            (680, "g", "potatoes", "Potatoes"),
            (12, "sausage", "skinny_sausage", "Skinny sausages"),
            (480, "g", "mixed_veg", "Vegetable medley"),
            (180, "g", "green_beans", "Green beans"),
            (15, "g", "light_spread", "Olive spread (or butter)"),
            (20, "g", "light_cream_cheese", "Light cream cheese"),
            ("Salt, pepper, paprika, garlic powder and mixed herbs",),
            ("Gravy, to serve (optional, not in the macros)",),
        ],
        steps=[
            "Cut the potatoes into 2cm cubes and boil in salted water for 15 minutes until tender.",
            "Spray the veg and green beans with Frylight, season and roast for 20 minutes at 200°C.",
            "Air fry the sausages at 190°C for 14 minutes (or oven bake for 18), turning halfway.",
            "Melt the spread in a pan, add the drained potatoes and mash.",
            "Stir in the cream cheese and season.",
            "Divide the mash, sausages and veg between 4 plates. Serve with gravy if you like.",
        ],
        tips="",
        swaps="Use any roast meat instead of the sausages, or veggie sausages to make it vegetarian.",
    ),
    dict(
        title="Hunters Chicken Loaded Potatoes", meal="Mains", main="Chicken",
        servings=1, macros=(454, 49, 50, 7), price=2.49, shop="Aldi",
        ingredients=[
            (150, "g", "chicken_cooked", "Pre-cooked chicken breast"),
            (200, "g", "potatoes", "White potato"),
            (15, "g", "bbq_sauce", "BBQ sauce"),
            (30, "g", "cheddar_rf", "Low-fat cheese"),
            ("Chilli powder, garlic granules, paprika, salt and pepper",),
        ],
        steps=[
            "Dice the potato into 2cm cubes and toss with the seasonings.",
            "Air fry for 15 minutes at 190°C (or oven bake for 20 at 200°C).",
            "Warm the BBQ sauce in a pan, add the chicken and break it apart. Season with salt, pepper, paprika and garlic powder.",
            "Pile the potatoes into a dish, top with the chicken and cheese, and microwave for 90 seconds to melt.",
            "Add more BBQ sauce over the top if you like.",
        ],
        tips="",
        swaps="Use any meat or veggie alternative. Peri peri sauce works great instead of BBQ.",
    ),
    dict(
        title="Chicken Stir Fry", meal="Mains", main="Chicken",
        servings=2, macros=(535, 64, 52, 9), price=2.66, shop="Asda",
        ingredients=[
            (300, "g", "chicken_breast", "Chicken breast, diced"),
            (600, "g", "stir_fry_veg", "Family stir fry veg bag"),
            (1, "onion", "onion", "Onion"),
            (45, "ml", "soy_sauce", "Light soy sauce (3 tbsp)"),
            (300, "g", "noodles_ready", "Ready-to-wok noodles"),
            ("Salt, pepper, garlic powder, paprika; sesame seeds to garnish",),
        ],
        steps=[
            "Fry the chicken in a wok, seasoning with salt, pepper, garlic powder, paprika and 1 tbsp soy sauce. Set aside once cooked.",
            "Fry the onion in the same wok for 3 minutes until softened.",
            "Add the stir fry veg, season the same way with another 1 tbsp soy, and fry for 5 minutes until halved in size.",
            "Add the noodles, the last tbsp of soy and the chicken. Season once more.",
            "Divide into 2 and garnish with sesame seeds.",
        ],
        tips="",
        swaps="Use any meat or veggie alternative, and any noodles you fancy.",
    ),
    dict(
        title="Chicken Wrap Pizzas", meal="Mains", main="Chicken",
        servings=2, macros=(467, 45, 44, 12), price=1.34, shop="Asda",
        description="Makes one tomato pizza (474 kcal) and one BBQ pizza (459 kcal). Macros shown are the average.",
        ingredients=[
            (200, "g", "chicken_breast", "Chicken breast"),
            (2, "wrap", "tortilla", "Tortilla wraps"),
            (1, "onion", "onion", "Red onion, diced"),
            (20, "g", "mushrooms", "Mushrooms, sliced"),
            (15, "g", "tomato_puree", "Tomato purée"),
            (25, "g", "bbq_sauce", "BBQ sauce"),
            (10, "g", "sweetcorn", "Sweetcorn"),
            (50, "g", "cheddar_rf", "Reduced-fat cheese"),
            ("Mixed herbs, garlic powder, salt and pepper",),
        ],
        steps=[
            "Season the chicken and oven cook for 20 minutes at 180°C (or air fry for 14).",
            "Fry the onion for 3–4 minutes. Set half aside and fry the mushrooms with the rest.",
            "Mix the tomato purée with salt, pepper, herbs, garlic powder and a splash of water to make a sauce.",
            "Slice the chicken. Spread one wrap with the tomato sauce and the other with BBQ sauce.",
            "Top the BBQ pizza with chicken, sweetcorn, onion and cheese, and the tomato pizza with chicken, mushrooms, onion and cheese.",
            "Bake at 200°C for 5 minutes, then sprinkle with mixed herbs.",
        ],
        tips="Use whatever toppings you like.",
        swaps="Use any meat or veggie alternative.",
    ),
    dict(
        title="Beefy Beef Sandwich", meal="Mains", main="Beef",
        servings=2, macros=(555, 49, 54, 17), price=2.26, shop="Aldi",
        ingredients=[
            (200, "g", "beef_steak_thin", "Thin-cut beef steak"),
            (2, "roll", "panini_roll", "Panini rolls"),
            (1, "onion", "onion", "White onion"),
            (100, "g", "mushrooms", "Mushrooms"),
            (50, "g", "cheddar_rf", "Reduced-fat cheddar"),
            ("1 tsp mild French mustard",),
            ("Salt, pepper, garlic powder and Worcestershire sauce",),
        ],
        steps=[
            "Thinly slice the onion, mushrooms and steak.",
            "Fry the onion on a medium-high heat until softened.",
            "Add the steak and season with salt, pepper, garlic powder and Worcestershire sauce.",
            "Add the mushrooms, then the mustard.",
            "Slice the rolls and fill each with half the beef and half the cheese.",
            "Grill for 3 minutes until the cheese melts.",
        ],
        tips="",
        swaps="",
    ),
    dict(
        title="Mexican Lasagna", meal="Mains", main="Beef",
        servings=5, macros=(485, 41, 39, 17), price=1.84, shop="Aldi / Asda",
        ingredients=[
            (3, "wrap", "tortilla", "Tortilla wraps"),
            (500, "g", "beef_mince_5", "5% fat beef mince"),
            (1, "packet", "seasoning_pack", "Taco seasoning"),
            (2, "onion", "onion", "Onions, diced"),
            (2, "pepper", "pepper", "Peppers, diced"),
            (250, "g", "mozzarella", "Grated mozzarella"),
            (400, "g", "chopped_tomatoes", "Chopped tomatoes (1 tin)"),
            (240, "g", "kidney_beans", "Red kidney beans, drained (1 tin)"),
            ("Salt, pepper, paprika and garlic powder",),
        ],
        steps=[
            "Preheat the oven to 200°C. Fry the onions for 3–4 minutes until softened.",
            "Add the mince and season with salt, pepper, paprika, garlic powder and half the taco seasoning.",
            "Once browned, add the peppers and cook for 3 minutes.",
            "Add the beans and tomatoes and season again with the rest of the taco seasoning.",
            "Layer: meat, 25g mozzarella, then 1½ wraps to cover. Repeat.",
            "Finish with the rest of the meat and the remaining 200g of cheese.",
            "Bake for 15 minutes, then rest for 5–10 minutes before slicing.",
        ],
        tips="Save most of the cheese for the top.",
        swaps="Use a veggie mince to make it vegetarian.",
    ),
    dict(
        title="World's Easiest Chicken Dinner", meal="Mains", main="Chicken",
        servings=2, macros=(366, 37, 33, 8), price=2.70, shop="Asda",
        ingredients=[
            (300, "g", "chicken_breast", "Chicken breasts (2)"),
            (350, "g", "mixed_veg", "Mixed veg (1 bag)"),
            (360, "g", "baby_potatoes_herb", "Buttery & herby baby potatoes (1 pack)"),
            (100, "ml", "gravy", "Gravy"),
            ("Spice mix: 1 tsp each garlic powder, paprika, mixed herbs and black pepper; ½ tsp chilli flakes; ½ tsp salt",),
        ],
        steps=[
            "Mix the spices together in a mug.",
            "Put the veg on one tray and the chicken on another, and coat each with half the spice mix.",
            "Roast for 20 minutes at 180°C.",
            "With 8 minutes to go, microwave the potatoes as per the pack.",
            "Make the gravy as per the pack.",
            "Slice the chicken and plate everything up.",
        ],
        tips="",
        swaps="Use a veggie alternative to the chicken, and any side potatoes you like.",
    ),

    # ---------------------------------------------------------------- MEAL PREP
    dict(
        title="Chicken Fajita Salad", meal="Meal prep", main="Chicken",
        servings=4, macros=(420, 38, 31, 14), price=2.40, shop="Aldi / Asda",
        ingredients=[
            (500, "g", "chicken_breast", "Chicken breast"),
            (2, "onion", "onion", "White onions"),
            (2, "pepper", "pepper", "Peppers"),
            (300, "g", "avocado", "Avocado (1 medium)"),
            (300, "g", "tomatoes", "Tomatoes"),
            (2, "head", "romaine", "Romaine lettuce"),
            (200, "g", "cucumber", "Cucumber (½)"),
            (1, "packet", "seasoning_pack", "Fajita seasoning"),
            (150, "g", "salsa", "Salsa (dressing)"),
            (100, "g", "yog_ff", "Fat-free yoghurt (dressing)"),
            (15, "g", "light_mayo", "Light mayo (dressing)"),
            (15, "g", "sriracha", "Sriracha (dressing)"),
            ("1 tbsp lemon juice; jalapeños and a dash of their juice (optional)",),
        ],
        steps=[
            "Preheat the oven to 200°C.",
            "Slice the onions, peppers and chicken into a large ovenproof dish. Season with salt, pepper, garlic powder and three quarters of the fajita seasoning, and roast for 20 minutes.",
            "Slice the lettuce into the biggest bowl you have.",
            "Slice the tomatoes, avocado and cucumber and add to the bowl with the jalapeños if using.",
            "Mix the dressing ingredients and toss through the salad.",
            "Serve the chicken hot with the salad, or let it cool and mix in if storing.",
            "Divide into 4 portions.",
        ],
        tips="Add the dressing on the day you eat it to keep the salad crunchy. Cut everything to roughly the same size.",
        swaps="Use any protein or veg you fancy.",
    ),
    dict(
        title="Salt & Pepper Chicken Noodles", meal="Meal prep", main="Chicken",
        servings=4, macros=(407, 31, 65, 3), price=1.55, shop="Aldi",
        ingredients=[
            (250, "g", "egg_noodles_dry", "Egg noodles (dry weight)"),
            (320, "g", "chicken_breast", "Chicken breasts (2 medium)"),
            (2, "onion", "onion", "White onions"),
            (2, "pepper", "pepper", "Peppers"),
            (60, "g", "spring_onions", "Spring onions"),
            (60, "ml", "soy_sauce", "Light soy sauce (4 tbsp)"),
            (35, "g", "snp_seasoning", "Salt & pepper seasoning (1 packet)"),
            (15, "g", "cornflour", "Cornflour"),
        ],
        steps=[
            "Dice the chicken into 2cm cubes. Season with salt, pepper, garlic powder, a third of the seasoning packet, 1 tbsp soy sauce and the cornflour.",
            "Fry for 8 minutes until cooked through, then set aside.",
            "Cut the onions and peppers into 2cm pieces and fry in the same pan for 5–6 minutes, seasoning with another third of the packet and 1 tbsp soy.",
            "Cook the noodles as per the packet. Cut the white part of the spring onions into 2cm pieces and finely slice the green part for garnish.",
            "Add the noodles, chicken and spring onion whites to the pan with the last of the seasoning and soy.",
            "Divide into 4 and garnish with the spring onion greens.",
        ],
        tips="Keep the chicken, onion and pepper pieces the same size.",
        swaps="Use any protein or veggie alternative. Also great with rice or chips instead of noodles.",
    ),
    dict(
        title="Meatless Protein Pasta", meal="Meal prep", main="Pasta", veg="V",
        servings=2, macros=(470, 31, 66, 8), price=1.42, shop="Aldi",
        ingredients=[
            (100, "g", "pasta_dry", "Pasta (dry weight)"),
            (2, "onion", "onion", "Red onions"),
            (2, "carrot", "carrot", "Medium carrots"),
            (50, "g", "mozzarella", "Grated mozzarella"),
            (300, "g", "cottage_cheese_ff", "Fat-free cottage cheese"),
            (250, "g", "pasta_sauce", "Tomato & garlic pasta sauce"),
            ("50ml pasta water",),
            ("Parsley and red chilli flakes, to garnish",),
        ],
        steps=[
            "Cook the pasta as per the packet.",
            "Dice the onions and fry in a little Frylight.",
            "Dice the carrots, add to the pan, season with salt, pepper, paprika and garlic powder, and cook for 5 minutes.",
            "Save 50ml of pasta water. Blend the cottage cheese, pasta sauce, pasta water and cooked veg until smooth.",
            "Return the sauce to the pan and stir in the pasta.",
            "Add the mozzarella and season to taste.",
            "Divide into 2 and garnish with parsley and chilli flakes.",
        ],
        tips="Double up for 4 lunches. For a chunkier sauce, don't blend the veg.",
        swaps="Add any extra protein you like.",
    ),
]
