"""Macro Prep, Micro Budget — Dave Fell.

Extracted from the PDF, then reviewed. Macros and prices are per serving as printed;
ingredient quantities are for the whole batch (`servings` portions).
"""

BOOK = 'Macro Prep, Micro Budget'

RECIPES = [{'title': 'Raspberry Bakewell Overnight Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (432, 33, 47, 9),
  'price': 1.14,
  'shop': None,
  'ingredients': [(160.0, 'g', 'oats', 'Oats'),
                  (800.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (350.0, 'g', 'raspberries', 'Frozen Raspberries (1 bag)'),
                  (60.0, 'g', 'protein_powder', 'Vanilla Protein (2 scoops)'),
                  (30.0, 'g', 'ground_almonds', 'Ground Almonds'),
                  ('200ml Water',)],
  'steps': ['Combine 40g of oats and 50ml of water (or your milk of choice) into each container and smush it down to '
            'the bottom of the tub to form a base.',
            'Add 4-5 raspberries into each container.',
            'Take a large mixing bowl and add your fat- free Greek yoghurt, protein powder, ground almonds and the '
            'rest of your raspberries (unless you want to set some aside for decoration).',
            'Spoon 1/4 of this mixture into each container and smooth over the top.',
            'If you saved some raspberries for decoration, add them now. Put a lid on and pop in the fridge overnight '
            'or for a minimum of 3 hours.'],
  'tips': 'Try different flavour combinations by changing the fruits or yoghurt and protein flavours!',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 16, 'xref': 228}},
 {'title': 'Mixed Berry Overnight Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (432, 33, 58, 6),
  'price': 1.08,
  'shop': None,
  'ingredients': [(160.0, 'g', 'oats', 'Oats'),
                  (800.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (500.0, 'g', 'mixed_berries', 'Frozen Mixed Berries'),
                  (60.0, 'g', 'protein_powder', 'Vanilla Protein (2 scoops)'),
                  (10.0, 'g', 'honey', 'Honey'),
                  (20.0, 'ml', 'lemon_juice', 'Lemon Juice'),
                  (200.0, 'ml', 'milk_skimmed', 'Skimmed Milk')],
  'steps': ['Mix 300g of frozen mixed berries into a frying pan with 10g honey and 20ml lemon juice. Simmer this on a '
            'low heat until a jam mixture forms (approx. 5 mins). Use the back of a spoon to smush it down at '
            'intervals to help it along.',
            'Combine 40g of oats and 50ml of milk of choice (or water) into each container and smush it down to the '
            'bottom of the container to form a base.',
            'Take a large mixing bowl and add your fat-free Greek yoghurt, protein powder and the rest (200g) of your '
            'mixed berries.',
            'Spoon 2 tbsp of the yoghurt mixture into each container, over the oats.',
            'After your jam has cooled, add 1/8 of the mix over your yoghurt.',
            'Repeat steps 4 + 5 until all the ingredients are used.',
            'Put a lid on and pop in the fridge overnight or for a minimum of 3 hours.'],
  'tips': 'Get your berry jam going first so it has time to cool whilst you prep the other ingredients.',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 18, 'xref': 244}},
 {'title': 'Blueberry Overnight Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (370, 35, 47, 4),
  'price': 1.19,
  'shop': None,
  'ingredients': [(160.0, 'g', 'oats', 'Oats'),
                  (60.0, 'g', 'protein_powder', 'Protein Powder (Vanilla from B&M Bargains)'),
                  (200.0, 'ml', 'milk_skimmed', 'Skimmed Milk'),
                  (400.0, 'g', 'blueberries', 'Frozen Blueberries (1 bag)'),
                  (600.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  ('200ml Water',)],
  'steps': ['Combine 40g of oats and 50ml of milk into each tub. Mix and using a spoon, push down into the tub to form '
            'a base.',
            'Get a large mixing bowl and add your fat- free Greek yoghurt, protein and 300g of blueberries. Mix until '
            'fully combined.',
            'Layer 1/4 of this mix into each tub until all the mix is used. Then take your remaining 100g of '
            'blueberries and add 25g of them into each tub.',
            'Put a lid on and pop in the fridge overnight or for a minimum of 3 hours.'],
  'tips': 'Try different flavour combinations by changing the fruits or yoghurt and protein flavours!',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 20, 'xref': 260}},
 {'title': 'Dark Choc & Raspberry Overnight Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (446, 35, 52, 8),
  'price': 1.15,
  'shop': None,
  'ingredients': [(160.0, 'g', 'oats', 'Oats'),
                  (800.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (350.0, 'g', 'raspberries', 'Frozen Raspberries (1 bag)'),
                  (60.0, 'g', 'protein_powder', 'Chocolate Protein Powder (2 Scoops)'),
                  (10.0, 'g', 'cocoa', 'Cocoa Powder'),
                  (25.0, 'g', 'choc_chips', 'Dark Chocolate'),
                  (200.0, 'ml', 'milk_skimmed', 'Skimmed Milk')],
  'steps': ['Combine 40g of oats and 50ml of milk (or water) into each container and smush it down to the bottom of '
            'the container to form a base.',
            'Add 4-5 raspberries into each container.',
            'Take a large mixing bowl and add your fat- free Greek yoghurt, protein powder, cocoa powder and the rest '
            'of your raspberries (unless you want to set some aside for decoration).',
            'Grate up your chocolate. Add half to the bowl and mix.',
            'Spoon 1/4 of this mixture into each container, if you’ve got them, add your raspberries for decoration. '
            'Sprinkle the remainder of your chocolate over the top.',
            'Put a lid on and pop in the fridge overnight or for a minimum of 3 hours.'],
  'tips': 'Try different flavour combinations by changing the fruits or yoghurt and protein flavours!',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 22, 'xref': 276}},
 {'title': 'Blended Strawberry Oats',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (439, 26, 51, 14),
  'price': 1.15,
  'shop': None,
  'ingredients': [(180.0, 'g', 'oats', 'Oats'),
                  (200.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (300.0, 'g', 'strawberries', 'Fresh Strawberries'),
                  (75.0, 'g', 'protein_powder', 'Vanilla Protein Powder'),
                  (20.0, 'g', 'honey', 'Runny Honey'),
                  (120.0, 'ml', 'milk_skimmed', 'Skimmed Milk'),
                  ('1 tsp (5g) Vanilla Extract',),
                  (70.0, 'g', 'choc_chips', 'Dark Chocolate'),
                  (10.0, 'g', 'coconut_oil', 'Coconut Oil')],
  'steps': ['Peel and cut up your strawberries. Divide into 2.',
            'Add your oats, fat-free Greek yoghurt, milk, protein powder, honey, vanilla extract and 1/2 of your '
            'strawberries into a blender. Blend until smooth.',
            'Take the remainder of your strawberries and divide by 4. Add 1/4 into each of your containers.',
            'Pour 1/4 of your yoghurt mix into each container over the top of your strawberries.',
            'Melt your chocolate and coconut oil in the microwave in 10-second batches until fully melted.',
            'Spoon over 1/4 of your chocolate into each container. Tilt the container so that it forms an even layer.',
            'Add a lid and pop in the fridge until you’re ready to eat.'],
  'tips': 'The chocolate will only form a thin layer so if you want a thick chocolate shell then use more. This will '
          'increase the calories though.',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 24, 'xref': 291}},
 {'title': 'Strawberry Cheesecake Overnight Wheat Biscs',
  'meal': 'Breakfast',
  'main': 'Weetabix',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (446, 32, 69, 3),
  'price': 1.5,
  'shop': None,
  'ingredients': [(10.0, 'biscuit', 'wheat_biscuit', 'Wheat Biscuits'),
                  (200.0, 'ml', 'milk_skimmed', 'Milk of choice'),
                  (800.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (50.0, 'g', 'protein_powder', 'Vanilla Protein Powder'),
                  (580.0, 'g', 'strawberries', 'Fresh Strawberries (1 pack)'),
                  (20.0, 'g', 'honey', 'Honey')],
  'steps': ['Slice up all your strawberries and add half into a frying pan with 20g honey. Simmer on low until a jam '
            'forms and then allow to cool.',
            'Take 10 wheat biscuits and crush them up into fine crumbs.',
            'Add 200ml of your milk of choice (I used skimmed) and add 2 tbsp of it into each container. Press into '
            'the bottom of the tub to form a base.',
            'Take the rest of your strawberries and combine them with your fat-free Greek yoghurt and protein powder '
            'in a bowl.',
            'Take your protein yoghurt mix and lay over 2 tbsp onto the base. Spread over and even out. Add 1 tbsp of '
            'your jam mix into each (once cooled).',
            'Then repeat this process with your wheat biscuits, yoghurt and jam until all the mix is equally '
            'distributed amongst the jars.',
            'Optionally sprinkle 1 shortbread biscuit over the top (not included in the macros).',
            'Let cool, pop on a lid and put in the fridge overnight or until you’re ready to eat.'],
  'tips': 'Get your jam on as early as possible as it needs to cool down before adding to the mix. Try different '
          'flavour combinations by changing the fruits or yoghurt and protein flavours!',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 26, 'xref': 309}},
 {'title': 'Peanut Butter & Banana Overnight Wheat Biscs',
  'meal': 'Breakfast',
  'main': 'Weetabix',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 3,
  'description': None,
  'macros': (502, 37, 79, 4),
  'price': 1.16,
  'shop': None,
  'ingredients': [(6.0, 'biscuit', 'wheat_biscuit', 'Wheat Biscuits'),
                  (100.0, 'ml', 'milk_skimmed', 'Milk of choice'),
                  (600.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (40.0, 'g', 'protein_powder', 'Vanilla Protein Powder'),
                  (3.0, 'banana', 'banana', 'Bananas'),
                  (35.0, 'g', 'powdered_pb', 'Powdered Peanut Putter')],
  'steps': ['Peel 1 banana and cut and save 6 discs for decoration.',
            'Mash up the remainder of your bananas and crush up 6 Wheat Biscuits. Get them into a large mixing bowl '
            'and stir until fully combined.',
            'Optionally you can add sweetener at this stage to the base mixture. Then add your milk and combine '
            'everything.',
            'In a separate bowl, combine your Greek yoghurt, 20g powdered peanut butter and protein powder. Mix until '
            'fully combined.',
            'Then take your containers. Add 2 tbsp of your Wheat Biscuits mix and smooth out to form a base. Then add '
            '2 tbsp of your yoghurt mix over the top and even out.',
            'Repeat step 5 one more time until all the ingredients are used.',
            'Add 3 banana discs on top of each for decoration. Then make up a runny peanut butter mix using the '
            'remainder of your powdered peanut butter.',
            'Divide the peanut butter into 3 and layer over the top.',
            'Pop a lid on and put it in the fridge overnight or until you’re ready to eat.'],
  'tips': 'Try different flavour combinations by changing the fruits or yoghurt and protein flavours!',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan. You can also use regular peanut butter (or any other nut butter) instead of the powdered peanut '
           'butter if you don’t have it.',
  'photo': {'page': 28, 'xref': 328}},
 {'title': 'Biscoff Overnight Wheat Biscs',
  'meal': 'Breakfast',
  'main': 'Weetabix',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (459, 34, 65, 8),
  'price': 1.03,
  'shop': None,
  'ingredients': [(8.0, 'biscuit', 'wheat_biscuit', 'Wheat Biscuits'),
                  (200.0, 'ml', 'milk_skimmed', 'Milk of choice'),
                  (400.0, 'g', 'greek_yog_ff', 'Fat-Free Natural Yoghurt'),
                  (2.0, 'pudding', 'protein_pudding', 'Caramel Protein Puddings'),
                  (50.0, 'g', 'protein_powder', 'Vanilla Protein Powder'),
                  (8.0, 'biscuit', 'biscoff_biscuit', 'Biscoff Biscuits'),
                  (20.0, 'g', 'biscoff_spread', 'Biscoff Spread')],
  'steps': ['Take 2 wheat biscuits for each container and crush them up into fine crumbs.',
            'Add 50ml of your milk of choice (I used skimmed) to each and mix until thoroughly combined. Press into '
            'the container to form a base.',
            'Take your protein puddings and spread half a pudding over each base. Even out using the back of a spoon.',
            'In a bowl, combine your yoghurt, protein powder and 3 crushed biscoff biscuits. Mix until fully combined.',
            'Add 1/4 of your yoghurt mix into each container.',
            'Pop on a lid and put in the fridge overnight.',
            'Crush up 3 of your remaining biscoff biscuits into a crumb and then add 1/4 of the crumb into each '
            'container. Then add 1/2 of a solid biscuit and drizzle 5g of melted biscoff spread over the top.'],
  'tips': 'For best results, add the biscuit topping and spread just before you eat.',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 30, 'xref': 345}},
 {'title': 'Mango Overnight Wheat Biscs',
  'meal': 'Breakfast',
  'main': 'Weetabix',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 4,
  'description': None,
  'macros': (436, 33, 70, 3),
  'price': 1.22,
  'shop': None,
  'ingredients': [(8.0, 'biscuit', 'wheat_biscuit', 'Wheat Biscuits'),
                  (200.0, 'ml', 'milk_skimmed', 'Milk of choice (I used skimmed)'),
                  (800.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (60.0, 'g', 'protein_powder', 'Vanilla Protein Powder'),
                  (500.0, 'g', 'mango', 'Frozen Mango')],
  'steps': ['Take 2 wheat biscuits for each container and crush them up into fine crumbs. Add 50ml of your milk of '
            'choice (I used skimmed) to',
            'each and mix until thoroughly combined. Press into the container to form a base. Optionally you can add '
            'some sweetener to the bases.',
            'Add your protein powder and 400g of your mango into a blender along with a dash of water. Blend until '
            'smooth (add water as required to blend).',
            'In a bowl, combine your yoghurt and mango protein mix. Stir until fully combined.',
            'Add 1/4 of your yoghurt mix into each container.',
            'Add 25g of your remaining frozen mango into each container.',
            'Pop on a lid and put in the fridge overnight or a minimum of 2 hours.'],
  'tips': 'If you would prefer it chunkier rather than smooth, you can leave out blending it or set more mango aside.',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan.',
  'photo': {'page': 32, 'xref': 365}},
 {'title': 'Tropical Protein Smoothie',
  'meal': 'Breakfast',
  'main': 'Oats',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 2,
  'description': None,
  'macros': (403, 30, 52, 7),
  'price': 1.14,
  'shop': None,
  'ingredients': [(100.0, 'g', 'oats', 'Oats'),
                  (50.0, 'g', 'protein_powder', 'Vanilla Protein Powder'),
                  (160.0, 'g', 'mango', 'Frozen Mango'),
                  (160.0, 'g', 'pineapple', 'Frozen Pineapple'),
                  (150.0, 'ml', 'milk_skimmed', 'Milk of choice'),
                  ('100ml of Water (or a handful of ice)',)],
  'steps': ['Put all ingredients into a blender.', 'Blend until desired consistency (add more water as required).'],
  'tips': 'Please note that the recipe makes 2! Shake well before consuming the second portion if left overnight.',
  'swaps': 'Swap out the yoghurt and protein powder for your favourite dairy-free alternatives to make this recipe '
           'vegan. Try different flavour combinations by changing the fruits or yoghurt and protein flavours!',
  'photo': {'page': 34, 'xref': 382}},
 {'title': 'Ham & Cheese Croissants',
  'meal': 'Breakfast',
  'main': 'Pork',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 8,
  'description': None,
  'macros': (308, 20, 21, 16),
  'price': 0.79,
  'shop': None,
  'ingredients': [(8.0, 'croissant', 'croissant', 'Croissants'),
                  (400.0, 'g', 'ham', 'Smoked Ham'),
                  (8.0, 'slice', 'cheese_slice', 'Cheese'),
                  (64.0, 'g', 'mozzarella', 'Mozzarella')],
  'steps': ['Lay out all your croissants and cut them in half lengthways.',
            'Add 50g of your cooked ham to each of the 8 croissants.',
            'Add whatever sauce you like at this point (will affect the calories and macros).',
            'Take your cheese slices. Rip in half and add 1 to each of the 8 croissants.',
            'Top with 8g mozzarella.',
            'When it’s time to cook, I flattened mine and then baked them in the oven at 180 degrees Celsius for 10 '
            'minutes.'],
  'tips': 'You can either cook them all at once or cook the ones you are eating that day and leave the others or eat '
          'without grilling - that’s up to you! You also don’t happen to flatten them, this is optional.',
  'swaps': 'Swap out the ham for any cooked meat or cooked meat alternative you like!',
  'photo': {'page': 36, 'xref': 399}},
 {'title': 'Breakfast Burrito',
  'meal': 'Breakfast',
  'main': 'Pork',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (506, 44, 41, 19),
  'price': 1.92,
  'shop': None,
  'ingredients': [(4.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (6.0, 'egg', 'egg', 'Eggs'),
                  (6.0, 'sausage', 'chicken_sausage', 'Chicken Sausages'),
                  (8.0, 'medallion', 'bacon_medallion', 'Bacon Medallions'),
                  (80.0, 'g', 'spinach', 'Watercress, Rocket and Spinach'),
                  (80.0, 'g', 'mozzarella', 'Mozzarella')],
  'steps': ['Air fry your chicken sausages for 12 mins at 190 degrees Celsius (or in the oven for 15 mins). When there '
            'are 7 minutes left on the sausages, take',
            'them out, and flip them. Then add in your bacon medallions for the remainder of the time.',
            'Scramble your eggs however you like - for this recipe I microwaved mine for 1 minute and then 30-second '
            'intervals, stirring each time. Season with salt, pepper, paprika, lazy garlic and oregano.',
            'Assemble your burrito by adding 1/4 of your eggs on top of 1 wrap.',
            'Add 20g of mozzarella, 1 1/2 chicken sausages, 2 bacon medallions, 20g of your salad mix and whatever '
            'sauce you like.',
            'Wrap up into a burrito.',
            'Repeat steps 4-6 until all your ingredients are used.',
            'Eat as is or you can air fry for 6 minutes for a crispy exterior.'],
  'tips': 'If you don’t want to/can’t microwave your eggs then scramble them in a frying pan.',
  'swaps': 'Swap out the chicken sausages and bacon medallions to your favourite meat alternatives to make veggie.',
  'photo': {'page': 38, 'xref': 421}},
 {'title': 'Breakfast Bagel',
  'meal': 'Breakfast',
  'main': 'Pork',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (398, 37, 29, 14),
  'price': 1.71,
  'shop': None,
  'ingredients': [(4.0, 'bagel thin', 'bagel_thin', 'Bagel Thins'),
                  (8.0, 'chipolata', 'chicken_chipolata', 'Chicken Chipolatas'),
                  (8.0, 'medallion', 'bacon_medallion', 'Bacon Medallions'),
                  (2.0, 'egg', 'egg', 'Eggs'),
                  (100.0, 'g', 'egg_white_liquid', 'Liquid Egg Whites'),
                  (4.0, 'slice', 'cheese_slice', 'Cheese')],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Cook your chicken chipolatas for 16 minutes in total, flipping halfway through.',
            'Prepare your eggs by combining the whites and 2 whole eggs into a dish. Season with salt, pepper, paprika '
            'and garlic powder. Add into a muffin tray or small sheet tray.',
            'Put your eggs and bacon medallions into the oven for 8 minutes.',
            'Remove everything from the oven and lay out your bagel thin. Add whatever sauce you like at this point.',
            'Then slice your chicken sausages lengthways. Add a slice of cheese to the bottom of the bagel, lay over '
            'the bacon medallions, then your sausages and finally your egg. Add the top half of the bagel and wrap it '
            'in tin foil.',
            'Eat now or store in the fridge for when you’re ready to eat. Serve & enjoy!'],
  'tips': 'Toast the bagels before assembling if you like a toasted sandwich! For best reheating results, air fry in '
          'the foil for 5 minutes at 190 degrees Celsius.',
  'swaps': 'Use 4 whole eggs if you don’t have access to egg whites - this will increase the amount of calories '
           'though. Swap out the sausages and bacon for your favourite veggie alternatives to make veggie friendly.',
  'photo': {'page': 40, 'xref': 437}},
 {'title': 'Breakfast Muffin',
  'meal': 'Breakfast',
  'main': 'Pork',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 6,
  'description': None,
  'macros': (499, 34, 35, 25),
  'price': 1.07,
  'shop': None,
  'ingredients': [(6.0, 'muffin', 'english_muffin', 'English Muffins'),
                  (6.0, 'chipolata', 'chicken_chipolata', 'Chicken Chipolatas'),
                  (6.0, 'patty', 'pork_patty', 'Pork Patties'),
                  (6.0, 'egg', 'egg', 'Eggs'),
                  (6.0, 'slice', 'cheese_slice', 'Cheese')],
  'steps': ['Air fry your chicken chipolatas & pork patties at 190 degrees Celsius for 12 minutes, flipping halfway '
            'through.',
            'Prepare your eggs by adding them into a jug. Season with salt, pepper, paprika, Italian herbs and garlic '
            'powder. Add into a muffin tray or small sheet tray.',
            'Put your eggs into a preheated oven for 8 minutes at 190 degrees Celsius. Once cooked, slice your egg '
            'into 6 slices.',
            'Toast your muffins at this point.',
            'Once cooked, remove everything from the oven or air fryer and lay out your toasted muffin. Add whatever '
            'sauce you like at this point.',
            'Then slice your chicken sausages lengthways. Add a slice of cheese to the bottom of the muffin, then on '
            'top 1 pork patty, followed by 1 sausage and finally your egg. Add the top half of the muffin and wrap in '
            'tin foil.',
            'Repeat this step until all the ingredients are used.',
            'Eat now or store in the fridge and air fry for 5-6 minutes when ready to eat.'],
  'tips': 'Use a small parchment paper lined baking tray for your eggs for the best results.',
  'swaps': 'Try out different variations of this recipe by swapping the sausages and pork patty for different kind of '
           'meats or your favourite meat alternatives.',
  'photo': {'page': 42, 'xref': 453}},
 {'title': 'Smokey BBQ Beef Burrito',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (497, 39, 52, 13),
  'price': 1.75,
  'shop': None,
  'ingredients': [(4.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (500.0, 'g', 'beef_mince_5', '5% Steak Mince'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (1.0, 'pepper', 'pepper', 'Pepper'),
                  (1.0, 'packet', 'seasoning_pack', 'Smokey BBQ'),
                  ('2 tsp Lazy Garlic',),
                  (90.0, 'g', 'mozzarella', 'Mozzarella'),
                  (100.0, 'g', 'salsa', 'Salsa (optional)')],
  'steps': ['Place the minced beef into a large frying pan over medium-high heat. Using a spoon, break the beef into '
            'smaller pieces as it browns. Season with salt, pepper, 1tsp lazy garlic and 1/2 of your seasoning packet.',
            'Whilst the mince is cooking, finely dice your onions and pepper.',
            'Once the beef is browned add the diced onions and bell pepper.',
            'Optionally, for an extra burst of flavour, consider adding 100g of hot salsa.',
            'Stir the mixture and allow it to cook for 3-5 minutes.',
            'Add the remaining BBQ seasoning and tsp of lazy garlic over the mixture and continue to cook for another '
            '2 minutes. Season with salt and pepper to taste.',
            'Turn off the heat and top the mixture with mozzarella cheese. Stir until the cheese is fully melted and '
            'incorporated.',
            'Divide the filling into 4 equal portions and lay out the tortilla wraps. Place one portion of the filling '
            'onto each wrap. Then carefully roll up the tortillas, enclosing the filling like a burrito.',
            'If eating now, then air fry them for 6 minutes (or pan fry for 3 minutes each side). For any ones that '
            'you are eating later, wrap in tin foil.'],
  'tips': 'Allow burritos to cool before wrapping them in the tin foil for best results.',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 45, 'xref': 497}},
 {'title': 'Fajita Chicken Burrito',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (401, 40, 42, 7),
  'price': 1.84,
  'shop': None,
  'ingredients': [(4.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (600.0, 'g', 'chicken_breast', 'Diced Chicken Breast'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (1.0, 'pepper', 'pepper', 'Pepper'),
                  (2.0, 'tomato', 'tomato', 'Salad Tomatoes'),
                  (1.0, 'packet', 'seasoning_pack', 'Fajita Seasoning'),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  (150.0, 'g', 'salsa', 'Salsa (optional)'),
                  (85.0, 'g', 'jalapenos', 'Jalapeños')],
  'steps': ['Place your chicken breast in a frying pan over medium-high heat.',
            'As it cooks, season with salt, pepper, paprika, garlic powder and ½ the fajita seasoning and use a '
            'spatula to stir the chicken and ensure it is fully coated.',
            'Whilst that cooks, dice up your onions, pepper and salad tomatoes.',
            'Then add the two onions and 50g of salsa, allowing it to cook for 5 minutes.',
            'After this time, add the pepper and the tomatoes. Optionally, if you like it spicy, add some jalapeños at '
            'this point.',
            'Pour in the rest of your salsa and seasoning packet and thoroughly mix everything.',
            'Turn off the heat and generously sprinkle the mixture with mozzarella cheese. Stir until the cheese is '
            'fully melted and integrated.',
            'Divide the filling into 4 equal portions and lay out the tortilla wraps. Place one portion of the filling '
            'onto each wrap. Roll up the tortillas, enclosing the filling like a burrito.'],
  'tips': 'Allow burritos to cool before wrapping them in the tin foil for best results.',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 47, 'xref': 515}},
 {'title': 'Tuna Melt Wrap',
  'meal': 'Mains',
  'main': 'Fish',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (400, 37, 41, 9),
  'price': 1.09,
  'shop': None,
  'ingredients': [(4.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (4.0, 'tin', 'tuna_tin', 'Tinned Tuna'),
                  (1.0, 'onion', 'onion', 'Red Onion'),
                  (200.0, 'g', 'peas', 'Peas'),
                  (90.0, 'g', 'mozzarella', 'Mozzarella'),
                  (30.0, 'g', 'light_mayo', 'Lighter than Light Mayo'),
                  (10.0, 'g', 'sriracha', 'Sriracha')],
  'steps': ['In a bowl, combine your tuna, diced red onion, peas, light mayo, sriracha and 10g of your mozzarella.',
            'Season with salt, pepper, garlic powder and paprika and mix thoroughly to combine.',
            'Lay out a tortilla wrap. Add 20g of cheese and 1/4 of your tuna mix for each wrap.',
            'Roll into a burrito and wrap in tin foil.',
            'Enjoy hot or cold. If reheating from chilled - unwrap from the foil and air fry for 5-6 mins at 190 '
            'degrees Celsius.'],
  'tips': None,
  'swaps': 'Swap out the red onion and peas for any veggies you like! Sweetcorn works great here as well.',
  'photo': {'page': 49, 'xref': 531}},
 {'title': "Cajun 'Beef' & Egg Burrito",
  'meal': 'Mains',
  'main': 'Veggie',
  'tags': ['Meal prep'],
  'veg': 'V',
  'servings': 5,
  'description': None,
  'macros': (420, 28, 44, 12),
  'price': 1.39,
  'shop': None,
  'ingredients': [(5.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (500.0, 'g', 'quorn_mince', 'Quorn Mince'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (1.0, 'pepper', 'pepper', 'Pepper'),
                  (3.0, 'tomato', 'tomato', 'Salad Tomatoes'),
                  (100.0, 'g', 'mozzarella', 'Mozzarella'),
                  (4.0, 'egg', 'egg', 'Eggs'),
                  ('85g Jalapeños (optional, not in the macros)',),
                  ('Handful Coriander (optional, not in the macros)',)],
  'steps': ['Dice up your onions, pepper and tomatoes.',
            'Add them into a large frying pan and season with salt, pepper and cajun seasoning.',
            'After 4-5 mins, create a well in the centre and add a heaped tsp of garlic and chilli. Stir well.',
            'Add your mince of choice (I used Quorn) to the pan and cook through.',
            'Once cooked, take your 4 eggs and beat them in a separate jar/bowl. Set mince mix to one side and add the '
            'eggs to the frying pan. Scramble the eggs using one half of the pan.',
            'Once cooked, incorporate the eggs and mince mix together.',
            'Season one final time with salt, pepper and cajun seasoning.',
            'Optionally add jalapeños and fresh coriander at this stage and mix. Then turn off the heat and add your '
            'cheese. Mix until fully combined.',
            'Lay out a wrap on some tin foil and add 1/5 of your mix to the wrap. Wrap into a burrito and then wrap '
            'tightly in the foil. Repeat until all the mince mixture is used.'],
  'tips': 'Allow burritos to cool before wrapping them in the tin foil for best results.',
  'swaps': 'Swap the Quorn mince for any other kind of mince you like to increase the protein content.',
  'photo': {'page': 51, 'xref': 550}},
 {'title': 'Bolognese Burrito',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 7,
  'description': None,
  'macros': (419, 27, 51, 11),
  'price': 1.0,
  'shop': None,
  'ingredients': [(7.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (500.0, 'g', 'beef_mince_5', '5% Steak Mince'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (200.0, 'g', 'carrot_grated', 'Carrots'),
                  (500.0, 'g', 'jar_sauce', 'Bolognese Sauce'),
                  ('2 tsp Lazy Garlic',),
                  (150.0, 'g', 'mozzarella', 'Mozzarella'),
                  (100.0, 'g', 'peas', 'Peas')],
  'steps': ['Dice up your onions and carrots.',
            'Put them into a large frying pan on medium-high heat.',
            'After 4-5 mins, create a well in the centre and add your beef mince and then your lazy garlic. Stir well.',
            'Season with salt, pepper, paprika and oregano.',
            'Once the mince has browned, add your bolognese sauce and then rinse the jar out with a little bit of '
            'water, shake and add to the pan.',
            'Add your peas.',
            'Season one final time with salt, pepper and oregano.',
            'Then turn off the heat and add your cheese. Mix until fully combined.',
            'Lay out a wrap on some tin foil and add 1/7 of your mix to the wrap. Wrap into a burrito and then wrap '
            'tightly in the foil. Repeat until all the mince mixture is used.'],
  'tips': 'Allow burritos to cool before wrapping them in the tin foil for best results.',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 53, 'xref': 568}},
 {'title': 'Chicken Tikka Wrap',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 6,
  'description': None,
  'macros': (369, 24, 54, 6),
  'price': 1.06,
  'shop': None,
  'ingredients': [(6.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (400.0, 'g', 'chicken_breast', 'Chicken'),
                  (2.0, 'onion', 'onion', 'Red Onions'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (60.0, 'g', 'curry_paste', 'Tikka Masala Paste'),
                  (1.0, 'tin', 'chopped_tomatoes', 'Chopped Tomatoes', 400),
                  (100.0, 'g', 'rice_dry', 'White Rice'),
                  ('2 tsp Lazy Garlic',)],
  'steps': ['Get your chicken into a pan on medium-high heat and season with salt, pepper, 1 tsp curry paste and 1 tsp '
            'lazy garlic. Fry until fully cooked and then set aside.',
            'Dice up your onions and peppers whilst the chicken is cooking.',
            'Get your white rice onto a boil and cook as per packet instructions.',
            'Once chicken is cooked and removed from the pan, add your onions and peppers into the same pan on '
            'medium-high heat. Season as before in step 1.',
            'After the veggies develop some colour and have softened, add your chopped tomatoes, cooked white rice and '
            'chicken.',
            'Season one final time with tumeric, garam masala, paprika, chilli flakes, salt, pepper and the rest of '
            'your curry paste. Mix until fully combined.',
            'Allow to cool. Then get your wraps ready and on top of some tin foil.',
            'Add 1/6 of your chicken tikka mix into the middle of your wrap and wrap into a burrito.',
            'Repeat step 8 until all ingredients are used.'],
  'tips': 'Allow burritos to cool before wrapping them in the tin foil for best results.',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 55, 'xref': 584}},
 {'title': 'Jalapeño Popper Bagels',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (351, 41, 31, 6),
  'price': 1.81,
  'shop': None,
  'ingredients': [(4.0, 'bagel thin', 'bagel_thin', 'Bagel Thins'),
                  (400.0, 'g', 'chicken_breast', 'Chicken Breast'),
                  (6.0, 'medallion', 'bacon_medallion', 'Bacon Medallions'),
                  (170.0, 'g', 'jalapenos', 'Jalapeños'),
                  (1.0, 'onion', 'onion', 'Red Onion'),
                  (100.0, 'g', 'cream_cheese', 'Low-Fat Cream Cheese')],
  'steps': ['Season your chicken with salt, pepper, garlic granules, Italian herbs and chicken seasoning. Put it into '
            'the air fryer for 12 minutes at 190 degrees Celsius.',
            'Put your bacon medallions into the air fryer for 7 mins at 190 degrees Celsius.',
            'Dice up your red onion and jalapeños.',
            'Once the chicken and bacon are cooked, add to the chopping board and either using 2 knives or a knife and '
            'a dough scraper, chop everything up finely.',
            'Then add your cream cheese. Season one final time with salt, pepper, paprika and 1 tsp each of lazy '
            'garlic and chilli.',
            'Chop everything together for a further 3-4 minutes or until everything is roughly the same size.',
            'Add 1/4 of your filling into each bagel thin and then wrap tightly in clingfilm.'],
  'tips': 'Toast the bagels for an extra crunch!',
  'swaps': 'Play around with different veggie and meat combinations! Things that would also work great: turkey bacon, '
           'sweetcorn or pickles.',
  'photo': {'page': 57, 'xref': 600}},
 {'title': 'Salt & Pepper Chicken Loaded Chips',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (459, 43, 65, 5),
  'price': 1.75,
  'shop': None,
  'ingredients': [(1000.0, 'g', 'potatoes', 'White Potatoes'),
                  (600.0, 'g', 'chicken_breast', 'Diced Chicken Breast'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (15.0, 'g', 'soy_sauce', 'Soy Sauce'),
                  (85.0, 'g', 'curry_sauce_mix', 'Mayflower Curry'),
                  (10.0, 'g', 'flour', 'Plain White Flour'),
                  ('2 tbsp Chinese 5 Spice',),
                  ('2 tbsp Garlic Powder',),
                  ('2 tbsp Paprika',),
                  ('1 tbsp Chilli Flakes',),
                  ('1 tbsp Salt',),
                  ('1 tbsp Black Pepper',)],
  'steps': ['Cut up your potatoes into chip shapes. Using a kitchen towel, dry them.',
            'Make your spice mix by combining those listed left.',
            'Add your potatoes into a large mixing bowl and give them a few sprays of oil. Add 2 tbsps of your spice '
            'mix and coat the potatoes evenly in it.',
            'Put your potatoes into the air fryer for 20-25 mins at 190 degrees Celsius, making sure you flip halfway.',
            'Take your chicken and add 2 tbsp of your spice mix and 1 tbsp of plain white flour. Mix until the chicken '
            'is fully coated. Fry on a medium heat until the chicken is cooked through.',
            'Whilst the chicken cooks, chop your onions and peppers into 2cm cubes.',
            'Once your chicken is cooked, set aside. Add your onions and peppers to the same pan and fry on medium '
            'heat for 3-4 mins.',
            'Add the remainder of your spice mix and soy sauce to the pan and mix. Re-add your chicken back to the '
            'pan.',
            'Once everything is cooked, lay out 1/4 of your cooked potatoes in a tub. Top with 1/4 of your chicken mix '
            'and repeat until all ingredients are used.',
            'Prepare your Mayflower curry sauce (optional) as per packet instructions. Lay over the loaded chips.'],
  'tips': 'You can either top with the Mayflower Curry sauce or any other sauce that you want to use! I would '
          'recommend heating up the meal first before adding a fresh batch of sauce over the top, rather than storing '
          'with the sauce on top.',
  'swaps': 'Swap the chicken out for any other protein sauce whether beef, pork or your favourite veggie alternatives!',
  'photo': {'page': 59, 'xref': 618}},
 {'title': 'Cheesy BBQ Beef Quesadillas',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 5,
  'description': None,
  'macros': (447, 35, 53, 13),
  'price': 1.44,
  'shop': None,
  'ingredients': [(5.0, 'wrap', 'tortilla', 'Tortilla Wraps'),
                  (500.0, 'g', 'beef_mince_5', '5% Steak Mince'),
                  (2.0, 'onion', 'onion', 'Onions'),
                  (1.0, 'pepper', 'pepper', 'Pepper'),
                  (1.0, 'packet', 'seasoning_pack', 'Smokey BBQ'),
                  (1.0, 'tin', 'chopped_tomatoes', 'Chopped Tomatoes', 400),
                  ('2 tsp Lazy Garlic',),
                  (125.0, 'g', 'mozzarella', 'Mozzarella')],
  'steps': ['Start by frying off your beef in a medium-hot large pan or wok.',
            'Season with salt, pepper, paprika, 1 tsp of lazy garlic and 1/2 of your BBQ seasoning packet. Mix fully.',
            'Dice up your onions and peppers and add into the pan after the beef is 80% cooked. Fry off for 3-5 mins.',
            'Add your tin of chopped tomatoes, 1 tsp of lazy garlic and the remainder of your BBQ seasoning packet. '
            'Mix until fully combined and taste for seasoning - adding if required.',
            'Assemble your quesadilla by adding 1/5 of your beef mix onto one side of the wrap.',
            'Add 25g of mozzarella and whatever sauce you like on top of the cooked beef mix.',
            'Fold over in half and press down gently to seal the quesadilla. Then fry on a frying pan for 2-3 mins on '
            'each side. (Or you can cook in air fryer for 6 mins at 180 degrees Celsius).',
            'Repeat steps 5-7 until all your ingredients are used.'],
  'tips': 'You don’t have to make all the quesadillas at the same time! You can make the beef mince mix (steps 1-4) '
          'and store in the fridge until you’re ready to make the quesadilla using steps (5-9).',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 61, 'xref': 640}},
 {'title': 'BLT Pasta Salad',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 3,
  'description': None,
  'macros': (492, 54, 51, 7),
  'price': 2.48,
  'shop': None,
  'ingredients': [(350.0, 'g', 'chicken_breast', 'Chicken Breast (I used Cajun Sizzle Steaks)'),
                  (130.0, 'g', 'pasta_dry', 'Pasta (dry weight)'),
                  (2.0, 'head', 'romaine', 'Gem Lettuces'),
                  (150.0, 'g', 'cucumber', 'Cucumber'),
                  (240.0, 'g', 'tomatoes', 'Tomatoes'),
                  (6.0, 'medallion', 'bacon_medallion', 'Bacon Medallions'),
                  (80.0, 'g', 'jalapenos', 'Jalapeños (optional)'),
                  (100.0, 'g', 'greek_yog_ff', 'Fat-Free Greek yoghurt'),
                  (30.0, 'g', 'light_sauce', 'Peri Peri Garlic Sauce'),
                  (60.0, 'g', 'sriracha', 'Sriracha'),
                  ('1 tbsp Lazy Garlic',),
                  ('Salt, Pepper, Paprika',)],
  'steps': ['Air fry your chicken breasts for 12 mins at 190 degrees Celsius.',
            'Get your pasta on to cook as per packet instructions.',
            'Lay six bacon medallions on a sheet of tin foil. When there is 7 minutes left on the chicken, add the '
            'bacon to the air fryer.',
            'While that cooks, chop up your cucumber, gem lettuce, and tomatoes. Once cut, add them to a large mixing '
            'bowl.',
            'Optionally, for an extra kick, add 80g of jalapeños.',
            'For the dressing, combine your Greek yoghurt, peri peri garlic sauce, sriracha, lazy garlic, salt, pepper '
            'and paprika. Mix with a spoon until fully combined.',
            'Once your bacon, chicken and pasta are all cooked, slice up your bacon and chicken. Then add all 3 to the '
            'mixing bowl.',
            'Add your dressing to the mixing bowl and mix thoroughly until everything is coated.',
            'Portion out into 3, serve & enjoy!'],
  'tips': 'Make sure you wash your vegetables before making the salad. Taste the dressing for seasoning before adding '
          'to the bowl; if you don’t have any of the ingredients for it, you can sub out with your favourite sauces.',
  'swaps': 'You can sub out the sources of protein and lettuce for any of your favourite types.',
  'photo': {'page': 63, 'xref': 662}},
 {'title': 'Peri Peri Chicken Sliders',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep'],
  'veg': None,
  'servings': 6,
  'description': None,
  'macros': (399, 40, 38, 10),
  'price': 1.26,
  'shop': None,
  'ingredients': [(650.0, 'g', 'chicken_breast', 'Chicken Breast'),
                  (6.0, 'bun', 'bun_wholemeal', 'Buns of Choice (I used wholemeal)'),
                  (1.0, 'packet', 'seasoning_pack', 'Peri Peri Seasoning'),
                  (80.0, 'g', 'jalapenos', 'Jalapeños'),
                  (100.0, 'g', 'mozzarella', 'Grated Mozzarella'),
                  (200.0, 'g', 'onion_g', 'Onions (frozen or fresh)'),
                  (4.0, 'slice', 'cheese_slice', 'Cheese Slices')],
  'steps': ['Lightly coat the chicken with a few sprays of low calorie spray oil.',
            'Season the chicken with salt, pepper, paprika, garlic powder and your peri peri seasoning packet.',
            'Massage the chicken breast thoroughly until the seasoning fully coats it.',
            'Place the seasoned chicken in the air fryer at 190 degrees Celsius for 15-20 minutes or until it’s cooked '
            'through.',
            'Once cooked, transfer the chicken to a chopping board and use 2 forks to gently shred it. Set aside for '
            'later use.',
            'Cut the six bread buns horizontally into halves and remove the top half.',
            'Evenly distribute the shredded chicken on the bottom buns, followed by a layer of onions (I used frozen) '
            'and jalapeños.',
            'Top with four cheese slices and 80g of grated mozzarella.',
            'Add your preferred sauce at this stage to your taste. Place the other half of the bread buns on top.',
            'Optionally, make a garlic butter by melting light butter in the microwave before adding garlic and '
            'parsley. Then spread the garlic butter on the top of the bread buns at this stage.',
            'Sprinkle the remaining grated mozzarella over the top of the buns.',
            'Place the buns in the oven at 180 degrees Celsius for 8 minutes or until golden brown.'],
  'tips': 'Swap the buns used for your favourite kind! Swap the Use a food processor to shred chicken for any other '
          'protein/meat free alternative to your chicken to save time! make all kinds of delicious peri peri sliders.',
  'swaps': None,
  'photo': {'page': 65, 'xref': 684}},
 {'title': 'Omelette Breakfast Bake',
  'meal': 'Breakfast',
  'main': 'Pork',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (355, 37, 12, 15),
  'price': 1.44,
  'shop': None,
  'ingredients': [(8.0, 'egg', 'egg', 'Eggs'),
                  (300.0, 'g', 'cottage_cheese', 'Low-Fat Cottage Cheese'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (1.0, 'pepper', 'pepper', 'Pepper'),
                  (240.0, 'g', 'ham', 'Ham'),
                  (160.0, 'g', 'mixed_veg', 'Frozen Mixed Veg'),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  ('4 tsp Lazy Garlic',),
                  ('4 tsp Lazy Chilli',)],
  'steps': ['Preheat your oven to 180 degrees Celsius.',
            'Dice up your onion and pepper.',
            'Crack 2 eggs into each of your 4 dishes and add 75g cottage cheese to each. Stir well with a fork.',
            'Add 1/4 of your onion and pepper into each dish. Then add in 60g of cooked ham and 40g of frozen mixed '
            'vegetables.',
            'Season each dish with 1 tsp lazy garlic and 1 tsp lazy chilli, salt, pepper, paprika, all-purpose '
            'seasoning and Italian herbs.',
            'Mix until fully combined.',
            'Add 20g of mozzarella over the top of each dish and put in the oven for 20-25 minutes.'],
  'tips': 'Play around with different flavour combinations by changing the veggies used: spinach, tomatoes or fresh '
          'avocado would also work great with this.',
  'swaps': 'Make veggie either by leaving out the ham or subbing in your favourite meat alternative.',
  'photo': {'page': 68, 'xref': 743}},
 {'title': 'Lemon & Herb Chicken Rice',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (473, 47, 55, 8),
  'price': 1.77,
  'shop': None,
  'ingredients': [(200.0, 'g', 'rice_dry', 'Washed White Rice'),
                  (600.0, 'g', 'chicken_breast', 'Diced Chicken Breast'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (1.0, 'packet', 'seasoning_pack', 'Lemon + Herb'),
                  ('4 tsp Lazy Garlic',),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  (480.0, 'ml', 'stock', 'Chicken Stock'),
                  (100.0, 'g', 'salsa', 'Salsa (optional)'),
                  (20.0, 'g', 'lemon_juice', 'Lemon Juice')],
  'steps': ['Preheat the oven to 190 degrees Celsius.',
            'Measure out and wash your rice. Put 50g into each container.',
            'Put 150g of chicken into each container.',
            'Dice your onion and put 1/4 into each container.',
            'Dice your peppers and put 1/4 of your total diced peppers into each container.',
            'Add 1 tsp of lazy garlic and 1/4 of your Lemon and Herb seasoning into each container.',
            'Add 120ml of chicken stock to each container and mix until fully combined.',
            'Top each with 20g of cheese and then bake in the oven for 30 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this dish veggie. Swap out the lemon and '
           'herb seasoning packet to vary the flavours! Lidl also do Smokey BBQ and Peri Peri seasonings as part of '
           'the same range!',
  'photo': {'page': 70, 'xref': 761}},
 {'title': 'Tuna Pasta Bake',
  'meal': 'Mains',
  'main': 'Fish',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (561, 40, 70, 13),
  'price': 1.56,
  'shop': None,
  'ingredients': [(200.0, 'g', 'pasta_dry', 'Pasta of choice (dry weight)'),
                  (4.0, 'tin', 'tuna_tin', 'Tuna (in brine)'),
                  (80.0, 'g', 'mozzarella', 'Grated Mozzarella'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (200.0, 'g', 'mixed_veg', 'Frozen Mixed Veg'),
                  (200.0, 'g', 'cream_cheese', 'Low Fat Cream Cheese'),
                  (1000.0, 'g', 'jar_sauce', 'Tomato Pasta Sauce'),
                  ('4 tsp Lazy Garlic',),
                  ('4 tsp Lazy Chilli',),
                  ('320ml Water to rinse jars',)],
  'steps': ['Preheat the oven to 190 degrees Celsius.',
            'Dice up your onion.',
            'Add 50g pasta, 1 tin tuna (drained), 1/4 onion, 50g cream cheese, 1/2 jar tomato pasta sauce and 1 tbsp '
            'of lazy garlic and lazy chilli into each dish. Mix thoroughly.',
            'Rinse out the jars with water and add 80ml into each dish.',
            'Season with salt, pepper, paprika and Italian herbs. Mix until fully combined.',
            'Top each with 20g of Mozzarella and put into the oven for 25-30 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'You could swap out the tuna for any white fish or poultry.',
  'photo': {'page': 72, 'xref': 782}},
 {'title': 'Chilli Beef Rice',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (481, 38, 54, 11),
  'price': 1.68,
  'shop': None,
  'ingredients': [(200.0, 'g', 'rice_dry', 'Washed White Rice'),
                  (500.0, 'g', 'beef_mince_5', '5% Steak Mince'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (4.0, 'tomato', 'tomato', 'Salad Tomatoes'),
                  (1.0, 'packet', 'seasoning_pack', 'Chilli Con Carne Seasoning'),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  (480.0, 'ml', 'stock', 'Beef Stock'),
                  (100.0, 'g', 'salsa', 'Salsa (optional)'),
                  (85.0, 'g', 'jalapenos', 'Jalapeños (optional)')],
  'steps': ['Preheat the oven to 190 degrees Celsius.',
            'Measure out and wash your rice. Put 50g into each container.',
            'Put 125g of beef mince into each container.',
            'Season with salt, pepper, paprika, garlic powder, chilli powder and optionally chilli flakes.',
            'Dice your onion and put 1/4 into each container.',
            'Dice your peppers and put 1/4 of your total diced peppers into each container.',
            'Add 1/4 of your chilli con carne seasoning into each container. Add 20g jalapenos and 25g of salsa '
            '(optional) to each container.',
            'Add 120ml of stock to each container and mix until fully combined.',
            'Top each with 20g of cheese and then bake in the oven for 30 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 74, 'xref': 799}},
 {'title': 'Chicken Curry',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (497, 47, 66, 4),
  'price': 1.96,
  'shop': None,
  'ingredients': [(200.0, 'g', 'rice_dry', 'Washed White Rice'),
                  (600.0, 'g', 'chicken_breast', 'Diced Chicken Breast'),
                  (2.0, 'onion', 'onion', 'Red Onions'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (30.0, 'g', 'curry_paste', 'Curry Paste of choice'),
                  (200.0, 'g', 'peas', 'Frozen Peas'),
                  (150.0, 'g', 'carrot_grated', 'Carrot'),
                  (100.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (800.0, 'g', 'chopped_tomatoes', 'Chopped Tomatoes'),
                  ('360ml Water',),
                  ('Salt, Pepper, Garlic Powder, Paprika and Garam Masala',)],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'In a bowl or tub, add 100g of Greek yoghurt to your chicken and 4 tsp of curry paste. Season with salt, '
            'pepper, garlic powder, paprika, and Garam Masala. Mix well to fully coat and set aside.',
            'Measure out and wash your rice. Put 50g into each container.',
            'Dice your 2 onions and put ½ an onion into each container.',
            'Dice your peppers and put 1/2 of a pepper into each container.',
            'Dice your carrots and add 1/4 to each container.',
            'Add 50g peas to each container.',
            'Divide your seasoned chicken into 4 and add to each container.',
            'Add 80ml of water and 1/2 a tin (200g) of chopped tomatoes to each container and then mix until fully '
            'combined.',
            'Season one final time with salt, pepper, garlic powder, paprika, Garam Masala, and another 1/2 tsp of '
            'curry paste. Mix well to fully combine, and then bake in the oven for 30-35 minutes at 190 degrees '
            'Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this dish veggie. Try different curry '
           'variations of this recipe by changing the paste you use.',
  'photo': {'page': 76, 'xref': 815}},
 {'title': "'Chicken' Fajita Pasta",
  'meal': 'Mains',
  'main': 'Veggie',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (510, 35, 62, 10),
  'price': 1.71,
  'shop': None,
  'ingredients': [(200.0, 'g', 'pasta_dry', 'Pasta of choice'),
                  (500.0, 'g', 'chicken_breast', 'Quorn Chicken Pieces'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (1.0, 'packet', 'seasoning_pack', 'Fajita Seasoning'),
                  (1.0, 'tin', 'taco_beans', 'Tinned Taco Beans', 400),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  (480.0, 'ml', 'stock', 'Vegetable Stock'),
                  ('4 tsp Lazy Garlic',),
                  ('4 tsp Lazy Chilli (optional)',),
                  (85.0, 'g', 'jalapenos', 'Jalapeños (optional)')],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Measure out your pasta. Put 50g into each container.',
            'Put 125g of your chicken pieces into each container.',
            'Dice your onion and put 1/4 into each container',
            'Dice your peppers and put 1/2 of a pepper into each container.',
            'Add 1/4 of your taco beans into each container.',
            'Add 1 tsp of lazy garlic into each container.',
            'Add 1/4 of your fajita seasoning into each container.',
            'Season with salt, pepper, paprika & chilli powder.',
            'Optionally add jalapeños and chilli into each if you like it spicy.',
            'Add 120ml of stock to each container and mix until fully combined.',
            'Top each with 20g of cheese and then bake in the oven for 30 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken pieces for chicken to increase the protein content.',
  'photo': {'page': 78, 'xref': 835}},
 {'title': 'Creamy Chicken & Leek Pasta',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (514, 51, 49, 12),
  'price': 1.73,
  'shop': None,
  'ingredients': [(200.0, 'g', 'pasta_dry', 'Pasta of choice (dry weight)'),
                  (600.0, 'g', 'chicken_breast', 'Chicken Breast'),
                  (40.0, 'g', 'mozzarella', 'Grated Mozzarella'),
                  (400.0, 'g', 'leeks', 'Leeks'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (120.0, 'g', 'peas', 'Frozen Peas'),
                  (200.0, 'g', 'cream_cheese', 'Low-Fat Cream Cheese'),
                  ('4 tsp Lazy Garlic',),
                  ('1 Chicken Stock Cube',)],
  'steps': ['Preheat the oven to 190 degrees Celsius.',
            'Dice up your onion and leeks.',
            'Add 50g pasta to each dish.',
            'Add 150g chicken breast into each dish. Season with salt, pepper and 1 tsp lazy garlic.',
            'Add 1/4 of your onion and 1/4 of your leeks into each dish.',
            'Add 150ml of chicken stock to each dish. Season with oregano, and mix well until fully combined.',
            'Put into the preheated oven for 20 mins.',
            'After 20 minutes, remove the dishes and add 50g light cream cheese and 30g frozen peas to each dish. Mix '
            'until fully combined and then top with 10g mozzarella.',
            'Put back in the oven for 10 minutes at 190 degrees Celsius or until golden brown.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this dish veggie.',
  'photo': {'page': 80, 'xref': 852}},
 {'title': 'Easy Chicken Noodles',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (500, 45, 48, 13),
  'price': 1.8,
  'shop': None,
  'ingredients': [(600.0, 'g', 'chicken_breast', 'Diced Chicken Breast'),
                  (4.0, 'packet', 'instant_noodles', 'Maggi Noodle Packets'),
                  (360.0, 'g', 'mixed_veg', 'Frozen Mixed Veg'),
                  (100.0, 'g', 'spring_onions', 'Spring Onions'),
                  ('20g Lazy Garlic',),
                  ('20g Lazy Chilli',),
                  ('1 litre Cold Water',)],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Take your Maggi noodles packs and put 1 packet of noodles into each dish. I crushed the noodles up but '
            'this is optional. Put all the seasoning packets (4 total) to one side.',
            'Add 150g diced chicken breast into each dish.',
            'Season now with salt, pepper and the seasoning packet.',
            'Add 5g (1 tsp) of lazy garlic and lazy chilli into each dish.',
            'Add 80g frozen mixed vegetables into each.',
            'Separate the light and dark parts of your spring onions. Slice the white bits of your spring onions into '
            '1 cm pieces and add 1/4 of them into each dish. Finely slice the other bits and save for the garnish.',
            'Season with paprika and add 250ml of water to each dish. Mix each dish thoroughly until fully combined.',
            'Put in your preheated oven for 30 mins at 190 degrees Celsius.',
            'Garnish with the remainder of your spring onions and optionally some chilli flakes.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this dish veggie. Use any brand of '
           'instant noodles you like.',
  'photo': {'page': 82, 'xref': 868}},
 {'title': 'Lasagne',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (600, 49, 53, 20),
  'price': 1.88,
  'shop': None,
  'ingredients': [(175.0, 'g', 'lasagne_sheet', 'Lasagne Sheets'),
                  (500.0, 'g', 'jar_sauce', 'Lasagne Sauce'),
                  (2.0, 'onion', 'onion', 'Red Onions'),
                  (500.0, 'g', 'beef_mince_5', '5% Mince'),
                  (200.0, 'g', 'carrot_grated', 'Carrots'),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  (200.0, 'g', 'cream_cheese', 'Low-Fat Cream Cheese'),
                  (100.0, 'g', 'cottage_cheese', 'Cottage Cheese'),
                  (50.0, 'ml', 'milk_skimmed', 'Milk Of Choice (I Used Skimmed)'),
                  (35.0, 'g', 'parmesan', 'Parmesan Cheese')],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Dice up your onions and carrots. Fry them in a pan for 3-4 minutes until softened.',
            'Add your beef mince to the pan and season with 2 tsp lazy garlic, salt, pepper, paprika and Italian '
            'herbs.',
            'Once the mince is cooked through, add your jar of lasagne sauce and mix until fully combined.',
            'While the ingredients in the pan is cooking, prepare your white sauce by adding your low-fat cream '
            'cheese, cottage cheese, milk and parmesan into a blender. Blend until smooth.',
            'Assemble your lasagnes by adding 2 spoons of sauce into each dish. Then break up 1 lasagne sheet (raw) '
            'into each dish and top with 1/8 of your white sauce.',
            'Repeat step 6 one more time.',
            'Add any remaining sauce over the top.',
            'Add 20g of mozzarella over the top of each dish and put in the oven for 30 minutes.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 84, 'xref': 886}},
 {'title': 'Mexican Lasagne',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (546, 43, 48, 19),
  'price': 1.83,
  'shop': None,
  'ingredients': [(500.0, 'g', 'beef_mince_5', '5% Steak Mince'),
                  (1.0, 'tin', 'chopped_tomatoes', 'Chopped Tomatoes', 400),
                  (8.0, 'tortilla', 'mini_tortilla', 'Mini Tortilla Wraps'),
                  (1.0, 'packet', 'seasoning_pack', 'Chilli Con Carne Seasoning'),
                  (100.0, 'g', 'mozzarella', 'Mozzarella'),
                  (500.0, 'g', 'mixed_veg', 'Mexican Vegetable Mix (frozen)')],
  'steps': ['Preheat the oven to 190 degrees Celsius.',
            'Make a quick chilli by frying off your mince, Mexican vegetable mix, chopped tomatoes and chilli '
            'seasoning for 6-8 minutes or until the mince is browned off. Season with garlic, paprika, salt and '
            'pepper.',
            'Add an even layer of your chilli into each of your glass dishes and spread out so it covers the bottom.',
            'Tuck 1 mini tortilla into the dish over the mix and 5g mozzarella.',
            'Repeat this process and add an even layer of your chilli to cover the wrap.',
            'Top with another mini tortilla wrap and then add 1/4 of the remaining mixture over the top.',
            'Top each with 20g of cheese and then bake in a preheated oven for 15 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 86, 'xref': 902}},
 {'title': 'Creamy Rosa Pasta',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (533, 53, 49, 13),
  'price': 1.77,
  'shop': None,
  'ingredients': [(600.0, 'g', 'chicken_breast', 'Chicken Breast'),
                  (200.0, 'g', 'pasta_dry', 'Pasta (dry weight)'),
                  (2.0, 'tin', 'chopped_tomatoes', 'Chopped Tomatoes', 400),
                  (200.0, 'g', 'cream_cheese', 'Light Cream Cheese'),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  (20.0, 'g', 'tomato_puree', 'Tomato Puree'),
                  (1.0, 'onion', 'onion', 'Red Onion'),
                  (200.0, 'g', 'mixed_veg', 'Mixed Frozen Veg'),
                  ('200ml Water',)],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Dice up your onion.',
            'Put 50g pasta and 150g chicken breast into each dish.',
            'Add 1/4 of your onion into each. Season at this stage with salt, pepper, paprika, and a tsp of lazy '
            'garlic and tomato puree.',
            'Add in 200g chopped tomatoes, 50ml of water, 50g mixed frozen veg, and 50g of light cream cheese into '
            'each dish. Mix thoroughly until everything is combined.',
            'Add 20g of mozzarella over the top of each dish and put in the oven for 30 minutes.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this dish veggie.',
  'photo': {'page': 88, 'xref': 918}},
 {'title': 'Chicken & Chorizo Pasta',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (542, 45, 52, 16),
  'price': 1.56,
  'shop': None,
  'ingredients': [(400.0, 'g', 'chicken_breast', 'Chicken Breast'),
                  (200.0, 'g', 'pasta_dry', 'Pasta (dry weight)'),
                  (2.0, 'tin', 'chopped_tomatoes', 'Chopped Tomatoes', 400),
                  (80.0, 'g', 'mozzarella', 'Mozzarella'),
                  (100.0, 'g', 'chorizo', 'Sliced Chorizo'),
                  (240.0, 'g', 'mixed_veg', 'Mixed Frozen Veg'),
                  ('200ml Water',),
                  ('4 Tsp Lazy Garlic',),
                  ('4 Tsp Lazy Chilli',),
                  (80.0, 'g', 'jalapenos', 'Jalapeños (optional)')],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Put 50g pasta and 100g chicken breast into each dish.',
            'Season at this stage with salt, pepper, paprika, chicken seasoning and a tsp each of lazy garlic and lazy '
            'chilli.',
            'Add 200g chopped tomatoes, 50ml of water, and 80g mixed frozen veg to each dish. Mix thoroughly until '
            'everything is combined.',
            'Add 20g of mozzarella over the top of each dish.',
            'Add 25g of chopped chorizo and optionally 20g sliced jalapeños onto each and put in the oven for 30 '
            'minutes.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken and chorizo for your favourite meat alternative to make this dish veggie.',
  'photo': {'page': 90, 'xref': 934}},
 {'title': 'Cottage Pie',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (474, 35, 52, 16),
  'price': 1.51,
  'shop': None,
  'ingredients': [(900.0, 'g', 'mash', 'Ready-Made Mash (2 x packs)'),
                  (500.0, 'g', 'beef_mince_5', '5% Steak Mince'),
                  (568.0, 'ml', 'gravy', 'Gravy'),
                  (640.0, 'g', 'mixed_veg', 'Frozen Mixed Vegetables'),
                  ('4 tsps Lazy Garlic',)],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Add 160g of frozen mixed vegetables into each dish.',
            'Break up 125g of beef mince into each container.',
            'Season each container with salt, pepper, paprika, oregano & 1 tsp of lazy garlic.',
            'Make up a pint (568ml) of gravy according to the packet instructions.',
            'Add 1/4 of your gravy to each dish and stir thoroughly until fully combined.',
            'Spread over 1/2 pack of ready-made mashed potatoes onto each and smooth over the top.',
            'Put in a preheated oven at 190 degrees Celsius for 25 mins.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this dish veggie. Feel free to make '
           'your own homemade mash if you don’t want to use the store bought version!',
  'photo': {'page': 92, 'xref': 950}},
 {'title': 'Creamy Chicken Fajita Pasta',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (528, 51, 54, 13),
  'price': 1.91,
  'shop': None,
  'ingredients': [(200.0, 'g', 'pasta_dry', 'Pasta of choice (dry weight)'),
                  (600.0, 'g', 'chicken_breast', 'Chicken Breast'),
                  (80.0, 'g', 'mozzarella', 'Grated Mozzarella'),
                  (1.0, 'onion', 'onion', 'Onion'),
                  (2.0, 'pepper', 'pepper', 'Peppers'),
                  (200.0, 'g', 'cream_cheese', 'Low-Fat Cream Cheese'),
                  ('4 Tsp Lazy Garlic',),
                  (1.0, 'packet', 'seasoning_pack', 'Fajita Seasoning Packet'),
                  ('1 Chicken Stock Cube (to mix with 450ml boiling water)',)],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Dice up your onion and peppers.',
            'Add 50g pasta, 150g diced chicken breast, 1/2 pepper, 1/4 onion, 50g cream cheese, 110ml of your chicken '
            'stock and 1 tbsp of lazy garlic into each dish. Mix thoroughly.',
            'Season each dish with salt, pepper, paprika and 1/4 of your fajita seasoning.',
            'Top each with 20g of Mozzarella and put into the oven for 25-30 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this dish veggie.',
  'photo': {'page': 94, 'xref': 968}},
 {'title': 'Chipotle Beef Rice',
  'meal': 'Mains',
  'main': 'Beef',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (563, 40, 71, 13),
  'price': 1.69,
  'shop': None,
  'ingredients': [(200.0, 'g', 'rice_dry', 'Washed White Rice'),
                  (500.0, 'g', 'beef_mince_5', '5% Steak Mince'),
                  (200.0, 'g', 'onion_g', 'Onions (frozen or fresh)'),
                  (240.0, 'g', 'mixed_veg', 'Frozen Mixed Veg'),
                  (800.0, 'g', 'chopped_tomatoes', 'Chopped Tomatoes'),
                  (200.0, 'g', 'cream_cheese', 'Light Cream Cheese'),
                  (60.0, 'g', 'chipotle_paste', 'Chipotle Paste'),
                  ('320ml Cold Water',),
                  (170.0, 'g', 'jalapenos', 'Jalapeños (optional)'),
                  ('4 tsp Lazy Garlic',),
                  ('4 tsp Lazy Chilli',)],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Measure out and wash your rice. Put 50g into each container.',
            'Put 125g of beef mince into each container.',
            'Season with salt, pepper, paprika, 15g chipotle paste, 1tsp each of lazy chilli and garlic for each '
            'container.',
            'Add 50g of onion and 80g of mixed vegetables into each container.',
            'Add 1/2 a tin of chopped tomatoes into each container. Rinse out the tins with 320ml of water and add '
            '80ml to each.',
            'Add 50g of light cream cheese to each container.',
            'If you want to add jalapeños, drain the jar and add 1/4 of it into each container.',
            'Mix until fully combined.',
            'Bake in the oven for 30 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the beef mince for your favourite meat alternative to make this recipe veggie!',
  'photo': {'page': 96, 'xref': 984}},
 {'title': 'Pesto Chicken Rice',
  'meal': 'Mains',
  'main': 'Chicken',
  'tags': ['Meal prep', 'One dish'],
  'veg': None,
  'servings': 4,
  'description': None,
  'macros': (507, 45, 54, 13),
  'price': 1.52,
  'shop': None,
  'ingredients': [(200.0, 'g', 'rice_dry', 'Washed White Rice'),
                  (600.0, 'g', 'chicken_breast', 'Diced Chicken Breast'),
                  (200.0, 'g', 'mixed_veg', 'Frozen Mixed Veg'),
                  (200.0, 'g', 'greek_yog_ff', 'Fat-Free Greek Yoghurt'),
                  (300.0, 'g', 'cherry_tomatoes', 'Baby Plum Tomatoes'),
                  ('4 tsp Lazy Garlic',),
                  (80.0, 'g', 'pesto_green', 'Green Pesto'),
                  (480.0, 'ml', 'stock', 'Chicken Stock')],
  'steps': ['Preheat your oven to 190 degrees Celsius.',
            'Measure out and wash your rice. Put 50g into each container.',
            'Put 150g of chicken into each container.',
            'Season at this stage with salt, pepper and Italian herbs. Then add 20g of green pesto and 1 tsp of lazy '
            'garlic into each.',
            'Add 50g of your fat-free Greek yoghurt into each. Also add 1/4 of your baby plum tomatoes, that have been '
            'sliced and 50g of frozen mixed vegetables.',
            'Add 120ml of chicken stock to each container and then mix until fully combined.',
            'Bake in the oven for 30 mins at 190 degrees Celsius.'],
  'tips': 'If there’s any liquid left in the dishes after the cooking time, allow them to cool for 10 minutes and it '
          'will absorb in this time. Be careful with the dishes when removing from the oven; they will be extremely '
          'hot!',
  'swaps': 'Swap out the chicken for your favourite meat alternative to make this dish veggie.',
  'photo': {'page': 98, 'xref': 1003}}]
